### ISSUE TITLE
Mousecape doesn't apply on startup June 23 2019 part 2

### ISSUE THREAD

**Issue by mac4kent** [alexzielenski/Mousecape#102]
June 23, 2019
Congratulation I am really proud of you did made it v0.0.6b2

Don't forget about MacOS 10.14.5 or MacOS 10.15 (come soon) and use Mousecape.app 0.0.7 (new version in future) easy to startup when "File > Export Startup Item" in once will auto install itself without hard to find script Autuomatic.app
<img width="1500" alt="Startup mousecape 0_0_7 June_23_2019" src="https://user-images.githubusercontent.com/4253305/59983405-f4d8d580-95d3-11e9-9f2c-3a10be3b496a.png">
 [LINK](https://github.com/alexzielenski/Mousecape/issues/96)

*** Add Feature ***
After "Export Startup Item" then Restart then Mousecape can be apply on startup.

This picture I am use Affinity Designer.app v1.7.1
I just suggest you let you know.

**Comment by alexzielenski** [comment]
The Mousecape helper tool is intended to solve this use case. I understand it is fairly buggy for some people. Looking into this.
