### ISSUE TITLE
Mousecape crashes constantly (Mojave 10.14.5 and 6)

### ISSUE THREAD

**Issue by jsteweii** [alexzielenski/Mousecape#103]
As much as I love Mousecape, I see a lot of issues with it on Mojave. It worked perfectly for me in Sierra and High Sierra, but in Mojave it's really a pain. I'm on 10.14.6.

It crashes a lot, in all kinds of scenarios. Primarily when waking from sleep or reboot/logout/login but also sometimes when coming from screensaver and occasionally when opening apps. I've tried the fixes described in other threads and removed/reinstalled with no improvement. Also helper is installed. Any help is appreciated.

So, is the project still alive or shouldn't I get my hopes up for a new version?

Thx in advance,

-johnny.

UPDATE: I ended up removing it again, running Onyx, and running an app called Omnidisksweeper where I found some leftovers from Mousecape and removed them also. I then reinstalled and it seems to have taken care of the crashing, fingers crossed.

UPDATE 1: So the problem is back. I have to reinitialise the cape I want active whenever I return from screensaver etc. So the original question about an update is still valid. 

Update 2: I've had a look at what's going on and it seems that when ever Mousecape crashes it's due to not remembering the cape that was applied. In the plist in preferences for mousecloakhelper the entry of the cape applied disappears after a crash. So my guess is that Mousecape forgets what was applied and therefore mousecloakhelper doesn't reinitialise.

**Comment by alexzielenski** [comment]
I'm interested in fixing this. Does this still occur for you?

**Comment by jsteweii** [comment]
Hi, thanks for responding. Yes it does. My description in open issues, on GitHub, is still what I get. I haven’t moved to Catalina and won’t be for the time being. What  an I help with?

**Comment by alexzielenski** [comment]
Would it be possible for you to upload a crash log? Your console app should have it somewhere

**Comment by jsteweii** [comment]
Sure, I'll upload one in the morning. It's almost midnight where I live.

**Comment by jsteweii** [comment]
Here you go: 

https://www.dropbox.com/s/j0x4h3yjnehe664/com.alexzielenski.mousecloakhelper_2019-10-12-114606_duck-Macbook-Pro.crash?dl=0

**Comment by alexzielenski** [comment]
Thank you for crash report! Wow it was due to the fact that I forgot to compile a file in the helper application included in mousecape used by the "Install Helper Tool". I had been testing on a different build scheme 🤦‍♂ 

Hopefully this will be resolved for you in next build which I intend to put out later today.

**Comment by jsteweii** [comment]
Ha ha, that's how the cookie crumbles sometimes. I'll try it out later today when I get home from work and let you know:-).

-johnny

**Comment by jsteweii** [comment]
Did you upload the new build? I only see 0.0.6b2 from last year. I see you made a new commit, which I can download, but unfortunately I don't know how to compile it.

-johnny

**Comment by jsteweii** [comment]
Did you upload the new build? I only see 0.0.6b2 from last year. I see you made a new commit to master, which I can download, but unfortunately I don't know how to compile it.

-johnny

**Comment by jsteweii** [comment]
It works beautifully so far, thank you so much😊.
