### ISSUE TITLE
hey, uh, Mousecape came as just a file, and I've tried converting it to an app and it doesn't work? help?

### ISSUE THREAD

**Issue by Arno-eats-souls** [alexzielenski/Mousecape#104]
idk if I'm being dumb or not but help please

**Comment by NordJan** [comment]
Dear Arno, yes.
You have to go to the releases section on GitHub (https://github.com/alexzielenski/Mousecape/releases <https://github.com/alexzielenski/Mousecape/releases>) and look at the latest assets, there is a .zip file containing the application.
Hope this helps.
