### ISSUE TITLE
animated gif 

### ISSUE THREAD

**Issue by abrarjaved644** [alexzielenski/Mousecape#105]
hey I have an animated gif which is 60 frames is there a way to make it into a cursor quick in photoshop it will take too long is there an automated way

**Comment by NordJan** [comment]
Dear Abrarjaved644, I think you are in the wrong place. This is about an application to change the looks of the cursor in macOS, nothing else much. Good luck.

**Comment by alexzielenski** [comment]
I dont have an automated way to do that, sorry.
