### ISSUE TITLE
Won't auto re apply

### ISSUE THREAD

**Issue by geeett** [alexzielenski/Mousecape#107]
i've tried everything and it just wont reapply when changed.

**Comment by jsteweii** [comment]
I think it's a dead project. I wrote him a few weeks ago, and have had no response. So it kind a works, but only as is. I have the same issue by the way.

**Comment by NordJan** [comment]
It might be dead, but this project is only a side-project for the creator, so if we are lucky there will be an update, otherwise it just works as it is.
Cheers, Nord
