### ISSUE TITLE
Cursor reset to default after reboot

### ISSUE THREAD

**Issue by jeremiastornado** [alexzielenski/Mousecape#109]
Using Mac Catalina, everytime I reboot the computer I have to make the changes again, is there a way to make this automatic?

**Comment by NordJan** [comment]
Make sure you have version 0.06 (not the beta), this should re-apply the chosen cursor set.
If not, have a look at a well-documented script from hipunk: https://github.com/alexzielenski/Mousecape/issues/96#issuecomment-466821416
I observed in my Catalina, the application can just be opened and closed to re-apply the cursor, so the script migth work when greatly simplified.
Cheers.

**Comment by alexzielenski** [comment]
As @NordJan responded, Mousecape since 0.0.6 solves issues with the helper tool.
