### ISSUE TITLE
cant open it on macOS Catalina, it says “Mousecape” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by taehyung00** [alexzielenski/Mousecape#110]

**Comment by NordJan** [comment]
Did you try to Right- (or Ctrl-) click and choose "Open" and then answer the dialogue to "Open" the app?

**Comment by lhaeger** [comment]
I've got the same on first try with "CTRL-Right-Click - Open", with no option to actually run mousecape.app. Second try then showed the well-known dialog including the "Open" button.

**Comment by alexzielenski** [comment]
Duplicate of #119 and #116

This was an issue with my erroneous uploading a build that was ad-hoc codesigned. Build 1813 should pass this check properly.

https://github.com/alexzielenski/Mousecape/releases/tag/1813
