### ISSUE TITLE
What default cursor does each cursor type correspond to?

### ISSUE THREAD

**Issue by Sweeper777** [alexzielenski/Mousecape#112]
I am quite confused by the available cursor types. I was able to find the default icon of some of them [here](https://support.apple.com/guide/mac-help/pointers-in-macos-mh35695/mac), but others, such as "Cell", "IBeamXOR" and "Counting Up", I don't know what they mean.

What is the default image of each cursor type?

**Comment by NordJan** [comment]
When you open the MouseCape application and select a cursorset, by clicking in the title part, next you right-click and select Edit, now you can see all the Types available.
What I did to save the default Apple set, first choose 'Restore Defaults' ( cmd+R) and next 'Dump Cursors ..'. You can look at their Type ans appreance to see what they mean.
