### ISSUE TITLE
Library doesn't open on launch of app

### ISSUE THREAD

**Issue by frankijean** [alexzielenski/Mousecape#114]
This issue may well be user error since I'm not versed in digital matters AT ALL :) 
I was unable to find a venue for asking about it so decided to try this. Hope that's not a problem.

Love this app so much and plan to share it with every single person I know!!!

**Comment by MUI68K** [comment]
I haven't seen this issue lately if I ever have. Could you try cleaning out the remaining Mousecape files but downloading for instance AppCleaner from [www.freemacsoft.net/appcleaner](url)

When cleaning - leave out the application and the "Application Support / Mousecape" directory as that's where your mouse cursors are placed. Don't want to lose those. It's probably just the Mousecape preferences file that's corrupt..

**Comment by frankijean** [comment]
Got it. I'll give it a try and report back. Thank you!

**Comment by MUI68K** [comment]
> Got it. I'll give it a try and report back. Thank you!

Any luck? 😃

**Comment by alexzielenski** [comment]
Would probably need more information to solve this problem. Since the original poster hasn't come back, im closing this. If the issue persists please reopen
