### ISSUE TITLE
Unsure 

### ISSUE THREAD

**Issue by icefirex09** [alexzielenski/Mousecape#115]
What is the type of mouse to use if you are planning to change the crosshair when you hover over a hyperlink. Just if this matters I am on mac. I have tried to change the mouse that i want to use to link and pointing at the same time but it doesn't

Thank you in advance.

**Comment by NordJan** [comment]
I am not sure if I fully understand your question, but below I have pasted part of my Mousecape-window. For me, the cursor I use for links is the '(left)hand with index finger pointing up', the type is called 'pointing', when editing the cursor-set.
![Screenshot 2020-05-05 at 13 50 03](https://user-images.githubusercontent.com/8850154/81063139-9361e280-8ed7-11ea-8ca6-8ed2320319a3.jpg)
Hope this helps. Cheers.

**Comment by icefirex09** [comment]
Damn I just realised I didn't even apply the mouse set that I was trying to use. Man I didn't use my brain at all. I am sincerely sorry for wasting your time.
-icefirex09
