### ISSUE TITLE
App crashs when opening

### ISSUE THREAD

**Issue by ademar111190** [alexzielenski/Mousecape#116]
I have been using the app for a while. everything normal. Starting today the app is crashing when I try to open it, I re-downloaded but the crash is still happening…

The crash:

```Process:               Mousecape [34287]
Path:                  /Applications/Mousecape.app/Contents/MacOS/Mousecape
Identifier:            com.alexzielenski.Mousecape
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mousecape [34287]
User ID:               501

Date/Time:             2020-05-06 11:44:11.021 -0300
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     4.4 (17P4281)
Anonymous UUID:        16106327-25E6-E44C-CB58-5CAA08177D54


Time Awake Since Boot: 4800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010cf38000-000000010cf66000 [  184K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   @L                          	0x0000000118ba1000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee2cc7bb8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000118ba1000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10cf38000 -        0x10cf65ff7 +@L (0) <E8388370-844D-3E9A-AE8E-A019835AA96F> @L
       0x118ba0000 -        0x118c31eff +@L (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> @L

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2998
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1040K resident=0K(0%) swapped_out_or_unallocated=1040K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             280K        3 
__DATA_CONST                        20K        1 
__LINKEDIT                         272K        2 
__TEXT                             768K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.3M       12 

Model: MacBookPro15,1, BootROM 1037.100.362.0.0 (iBridge: 17.16.14281.0.0,0), 6 processors, 6-Core Intel Core i7, 2,6 GHz, 16 GB, SMC 
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: Dell Universal Receiver
USB Device: DELL DA300
USB Device: USB3.1 Hub
USB Device: USB 10/100/1000 LAN
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
```

**Comment by fnankivell** [comment]
Got exactly the same thing starting this morning, glad to know I'm not the only one...

**Comment by NordJan** [comment]
At first I thought this didn't concern me, as I ran Mousecape earlier this week/weekend without problems, but now I check, it also happens here. 
I get this for the crash report "Termination Reason:    Namespace CODESIGNING, Code 0x1"
Nothing much changed on my system lately, but LockRattler reports an update of XProtect as of 2020-05-01 to version 2120. This happens 'silently' by Apple. Hope this helps.

**Comment by xd-Expert** [comment]
I redownloaded the mousecape app, and it worked perfectly. I recommend you try doing so.

**Comment by xd-Expert** [comment]
I actually had to download the previous version 006 b2, published two years ago.

**Comment by ademar111190** [comment]
The downgrade to the version 006 b2 did work here as well, thank you @xd-Expert

**Comment by DaniBedz** [comment]
> I actually had to download the previous version 006 b2, published two years ago.

Thanks so much for sharing this. I had no idea how much I would hate going back to the default OSX cursors!

**Comment by MUI68K** [comment]
I've built Mousecape from the latest Master -- enabling hardened runtime and cleared out the Sparkle Framework because Xcode complained about that too.
I've removed the references to that framework and right now Mousecape is up and running on macOS Catalina with no complaints about malware - which I also found odd.
I just fresh installed macOS Catalina yesterday and only got around to Mousecape today.

Right now Mousecape opens and applies cursor sets just fine.
Just a tip to others that has issues; that you can use Xcode to fix it up.

**Comment by NordJan** [comment]
@MUI68K : thanks for bringing this good news (that the issue can be fixed), for those able to work with Xcode. I tried, but my credentials are unknown to Apple and my knowledge of Xcode too little to fix this.
It seems this application has a dedicated fan-base, so I sincerely hope there will be another release for those.

**Comment by MUI68K** [comment]
@NordJan Agree on the future release of this app. I haven't been able to get in touch with the author for many months now. Usually, I get a response. Not with ThemeEngine and I doubt this time around as well.

I haven't got any developer credentials as such, that are active anyway, but I just turn off all the codesigning to be Signed to run Locally - there's a mention of Codesigning in the crash report in the first post here

> "Termination Reason:    Namespace CODESIGNING, Code 0x1"

Despite the very niche thing Mousecape does - it does certainly have a great following.

**Comment by NordJan** [comment]
@MUI68K : Thanks for your response. The tip to turn codesigning off did help in some way, but now I end up with so many other issues and I am too inexperienced with Xcode to even understand the messages.
I will try to reach the author to see if there is another release possible.

**Comment by fnankivell** [comment]
The issue I have with version 0.6b2 is that cursors don't re-apply at startup, have to manually open Mousecape to get cursors back. It's a trade-off I'm willing to live with to get my custom cursors fix ;)

**Comment by ademar111190** [comment]
Thanks @MUI68K removing the sparkle I'd manage to make a build, it is running as expected <3

I think it would be OK if someone publishes a version of this app with the fix meanwhile the author is offline.

**Comment by Tommasor14** [comment]
Has anybody found a solution?
thanks.

**Comment by MUI68K** [comment]
I've uploaded the latest Mousecape master from the official repo and as such this is the latest Mousecape version and I've only taken away the references to the Sparkle framework and ticked the Hardened Runtime checkbox in latest Xcode version for macOS Catalina 10.15.4. If this works on anything other than Catalina then that's great. I built it for macOS Mojave and beyond:
my Jumpshare account:
https://jumpshare.com/v/k9ftgJjkZZSjbeN4bzgU

**Comment by MUI68K** [comment]
_I'd just like to make the folks here in this issue aware of a new build that includes the Sparkle framework._

### Read more here: 
https://github.com/alexzielenski/Mousecape/issues/119#issuecomment-628637665

**Comment by alexzielenski** [comment]
This was an issue with my erroneous uploading a build that was ad-hoc codesigned. Build 1813 should pass this check properly.

https://github.com/alexzielenski/Mousecape/releases/tag/1813
