### ISSUE TITLE
“Mousecape” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by Dnilo** [alexzielenski/Mousecape#119]
I got this message today and I can't open it anymore.

![Screen Shot 2](https://user-images.githubusercontent.com/6490935/81367869-8eee2300-90ab-11ea-9cff-980eceb7dca4.png)

I tried to re-download it but it's still the same.

**Comment by Tommasor14** [comment]
I have the same problem here.
Did you solve it?

**Comment by MUI68K** [comment]
@Dnilo @Tommasor14 

**To anyone who is interested.**

I've uploaded the latest Mousecape master from the official repo and as such this is the latest Mousecape version and I've only taken away the references to the Sparkle framework and ticked the Hardened Runtime checkbox in latest Xcode version for macOS Catalina 10.15.4. 

_If this works on anything other than Catalina then that's great_
_I built it for macOS Mojave and beyond_

_**Link to Mousecape on my Jumpshare account:**_
https://jumpshare.com/v/k9ftgJjkZZSjbeN4bzgU

**Comment by Tommasor14** [comment]
@MUI68K It works!
Thank you very much!

**Comment by MUI68K** [comment]
> @MUI68K It works!
> Thank you very much!

Great! 👍

**Comment by Tommasor14** [comment]
I have a question though.
Is this a fixed version?  In case of new releases can I upload this one I have just downloaded?

Thanks in advance.

**Comment by MUI68K** [comment]
> I have a question though.
> Is this a fixed version? In case of new releases can I upload this one that I have just downloaded?
> 
> Thanks in advance.

It's a quick fix - as in, it was done by me, because I also ran into the issue of Mousecape failing to launch. 
The author, Alex, probably doesn't want it too many places on the Internet, but I don't know.

I'm sure he will come here one day and claim what is rightfully his and I will then take down my uploads of the versions of ThemeEngine and now Mousecape that I have _fixed_ and that I have uploaded to Jumpshare - I can luckily delete these files rather quickly should the need arise.

I'm uncertain as what to do from here. Where would you like to upload it to? I'm guessing you can keep this on hand in your own personal online storage service.

**Comment by Tommasor14** [comment]
Ok, I got it.
Btw the App works smoothly and without any issues. 
Let's keep use this one, until the owner fixes it in the future.
Btw thanks, I kept a copy for me.
 Oh yes, thank you ( and I speak for everybody ) because u fixed Mousecape.

It's true, not all the heroes wear a cape

**Comment by luckydonald** [comment]
Mojave works. Thanks. 
Why did you remove the auto updated though?
Wouldn't it make sense to get an update as soon as the main developer fixes this again?

**Comment by Dnilo** [comment]
Thank you so much, I got my cursor back!

I guess it's a small way to thank you, but I'll share my self made cursor in case anyone wants it.
https://www.dropbox.com/s/h3oj7wt7383l27x/Zombie%20cursor.zip?dl=1

**Comment by MUI68K** [comment]
> Mojave works. Thanks.
> Why did you remove the auto updated though?
> Wouldn't it make sense to get an update as soon as the main developer fixes this again?

I saw error references to that particular framework and I took, a probably unwise step, to remove the Sparkle.framework. It was how I was able to get a build working. The easy way out of it, you might call it.

I will of course, later this week, if my mood gets better, see if the Sparkle.framework can be included and let it auto update. I agree with what you say that when or if the the author comes back to update Mousecape - that at least we will all be prompted to update.

**Comment by MUI68K** [comment]
> Thank you so much, I got my cursor back!
> 
> I guess it's a small way to thank you, but I'll share my self made cursor in case anyone wants it.
> https://www.dropbox.com/s/h3oj7wt7383l27x/Zombie%20cursor.zip?dl=1

You're welcome, and thank you for sharing your work -- will take a look 😄

**Comment by MUI68K** [comment]
Hi, again.

I have made a new build with Sparkle framework included. Taken from the latest 0.0.6 build from the official repo for Mousecape and integrated that with the latest code, also from the official repo for Mousecape.

### **New link for those interested** 
**Note:** The application size has also gone up a bit with this build.
Direct link: https://jumpshare.com/v/eSrGrbM5XXLxVGwiwXK9+/Mousecape_May15withSparkleFramework_build.zip

**And screenshots here:**
<img width="1169" alt="Screen Shot 2020-05-14 at 15 29 01" src="https://user-images.githubusercontent.com/60530401/81940370-d1f24e00-95f7-11ea-8980-d856c9218c83.png">
<img width="1169" alt="Screen Shot 2020-05-14 at 15 29 12" src="https://user-images.githubusercontent.com/60530401/81940377-d3bc1180-95f7-11ea-857d-8ac15ca20fab.png">

Screen recording here:
https://jumpshare.com/v/2WxGSegzZmj3UbW7vuV0+/Screen+Recording+2020-05-14+at+15.22.42.mov

**Comment by Tommasor14** [comment]
Goodafternoon, does it mean that now updates are allowed and we can keep this version in our Mac instead of deleting it and installing the ''official one''? 
it would be great..
Thanks.

**Comment by MUI68K** [comment]
> Good afternoon, does it mean that now updates are allowed and we can keep this version in our Mac instead of deleting it and installing the ''official one''?
> it would be great..
> Thanks.

It means that if there's an update to Mousecape through official channel - from the author himself - that Mousecape ought to pick up on the update. So far, there isn't anything to test up against as there isn't any newer release other than 0.0.6. I'm crossing fingers for that it all pans out.
With what Mousecape 0.0.6 does on macOS Catalina 10.15.4 I don't know how to get access to updates to the app because the whole app is apparently blacklisted and flagged as malware or corrupted. There is of course the older 0.0.6b2 that we can use to check for updates to what could be 0.0.7 (just a guess) of Mousecape.

I'm only this vague in my explanation and primarily made this build to try and perhaps make a more complete build update to Mousecape that can be used with macOS Catalina 10.15.4 and has the same feature set as the latest official release that Alex Z. has on his repo.

I can see that using the Terminal command "nettop" that Mousecape contacts a server during the Check for Updates process. I can't find info on the server holder but I gather that it's the server for GitHub's update that Alex put into the Sparkle.framework.
 
I guess, that time will tell if it all proceeds to be beneficial to us all. Remember, I'm also using Mousecape myself and I also prefer that the update mechanism is A-OK.

While time is our worst enemy, next to the covid-19 pandemic and cancer and what else have you, we will have to see what's new when there's something pushed to the update channel.

It's a long way around actually answering the question you put forth. I hope that you understand that my intentions aren't malicious and that only try doing what I can with limited coding abilities - although they appear to be quite good - at least the part of using and transforming existing code.

The "nettop" Terminal command is entered just like this inside a Terminal window:
`nettop` 

Launch Mousecape and select the Check for Updates menuitem as see if you get an url like this:
`151.101.128.133:443`

I would be very surprised if this all doesn't match what I have. I'm in Denmark and I can't say with certainty if the server URL is the same the World over.

**Comment by mac4kent** [comment]
Mousecape.app 0.0.6 make bad crash while Catalina MacOS 10.15.5 BETA 
![1  MacOS 10 15 5 beta](https://user-images.githubusercontent.com/4253305/81957983-2c70b780-95c2-11ea-9830-153697959376.png)
S33 #118

**Comment by MUI68K** [comment]
> Mousecape.app 0.0.6 make bad crash while Catalina MacOS 10.15.5 BETA
> ![1 MacOS 10 15 5 beta](https://user-images.githubusercontent.com/4253305/81957983-2c70b780-95c2-11ea-9830-153697959376.png)
> S33 #118

One can only hope that the final release of 10.15.5 is right around the corner. I wanted to install the public beta earlier today, then I took a nap and now I think I'll just wait a while and see what is wrong. Are you using any of my linked versions of Mousecape or the one official by the author?

**Comment by izayoisama0987** [comment]
Hello. You are developing great software. By the way, this software could not be loaded on my MacBookPro2020. Do you know the solution? (Sorry, my English may not be good because I'm not in a country that normally speaks English.)

**Comment by NordJan** [comment]
No problem, we will try to help anyway ;-).
The most recent official version of Mousecape seems blocked by Apple, but you can try either the 0.06b2 version or the unofficial 'repaired' version by Allan, see further back in this issue.
Let me know if this helps.

**Comment by mac4kent** [comment]
@NordJan may I have link?

**Comment by NordJan** [comment]
@mac4kent a link to what?

**Comment by mac4kent** [comment]
@NordJan said "but you can try either the 0.06b2" I can't find b2

**Comment by NordJan** [comment]
@mac4kent it is the code tab and then under releases: https://github.com/alexzielenski/Mousecape/releases/tag/0.0.6b2

**Comment by mac4kent** [comment]
@NordJan Thank you for give me right link and open it work for sure on MacOS Catalina 10.15.5 Beta. I just did click Code and I can't find which version and I see only 7 month last they made update.

**Comment by izayoisama0987** [comment]
Thank you for your help. I tried 0.0.6b2 and it didn't work either. And I wasn't sure about the repaired version of the site. https://www.deviantart.com/allannyholm/art/Mousecape-Throwback-Mac-cursors-781872368
Is this this?

**Comment by NordJan** [comment]
No, that are the cursors (and more).
The "repaired" version of the application is in: https://github.com/alexzielenski/Mousecape/issues/119#issuecomment-628637665

**Comment by izayoisama0987** [comment]
Thank you for teaching me. But even if I use MouseCape from that site, I couldn't get MouseCape into my MacBook Pro2020.

**Comment by izayoisama0987** [comment]
My MacBook Pro recognized all MouseCape as malicious software. Do I need to change any settings?

**Comment by mac4kent** [comment]
If you get new computer, You have to use https://github.com/alexzielenski/Mousecape/releases/tag/0.0.6b2 and open if you see appear app.
I am not sure know yet about this previous on your other computer ~/library/Apple Support/mousecape. . . see picture
![image](https://user-images.githubusercontent.com/4253305/82847614-f5dd4b80-9ea3-11ea-8e49-099ec59b2338.png)

**Comment by NordJan** [comment]
> My MacBook Pro recognized all MouseCape as malicious software. Do I need to change any settings?

@izayoisama0987 : I would recommend the following steps:
- download a known working version of Mousecape (either the 0.06b2 or repaired one)
- unzip the .zip and move the application to your Application folder
- open the Mousecape application, if you get message that it can't be opened: right-click on the file, choose "Open", read the dialogue and open
- when opened, install the Mousecape helper tool (under Mousecape-menu-item)
- check that the .cape file is actually a xml-file, see previous screenshot
- open the .cape file
- within Mousecape double-click the cursor set to set this.

Let me know what does work and what doesn't, to find out where your problem is.

**Comment by izayoisama0987** [comment]
Thank you for teaching me carefully. I've done the third part of this procedure. But when I open the App, this screen appears.Where can I find helper tools?
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/65849452/82880795-dc0e3800-9f79-11ea-82d7-f3cd06202ed0.png">

**Comment by NordJan** [comment]
@izayoisama0987 OK, that is the repaired version you are using, I think. Can you try the 0.06b2 version? And what macOS version do you use?
As Mousecape is working for a lot of people, don't loose hope, we will try to get you going also.
For the helper tool, you need to get Mousecape running first, it is in its menu.

**Comment by mac4kent** [comment]
MacOS 10.15.5 Beta
Alchemy Beta.app 6.3.6.46699
See youtube https://youtu.be/-MCDXLFK1-U
Show long script on .txt unzip .zip
[Alchemy crash guide.txt.zip](https://github.com/alexzielenski/Mousecape/files/4682780/Alchemy.crash.guide.txt.zip)

**Comment by izayoisama0987** [comment]
I am impressed with your kindness. Thank you.
This is not a "repair" version. I am trying 0.06b2. The version I'm using is 10.15.4.

**Comment by NordJan** [comment]
Are you sure about the version? In your crash-report it says version 0.06 (1713); version 0.06b2 has version 0.06 (1656). This one is working for me, both om 10.15.4 and now on 10.15.5.
Try the version from Allan Nyholm at jumpshare: https://jumpshare.com/v/k9ftgJjkZZSjbeN4bzgU
That one is also working for me. Cheers.

**Comment by mac4kent** [comment]
@NordJan Yes I agree with you exactly this last link it work for me and 0.06b2 it work for me too on MacOS 10.15.5 Beta (19F94a) Catalina 
Yaaa ay good job.

**Comment by NordJan** [comment]
@mac4kent Thanks.
BTW: 10.15.5 is out of beta, the release version can be installed.

**Comment by mac4kent** [comment]
@NordJan Sure you are welcome. True. I still have beta to send FeedBack Assistant.app send to Apple Developers many times lot bug. about 100 send feedback I did.

**Comment by izayoisama0987** [comment]
I was able to download it successfully! thank you very much! But there was a problem. It did not support my mouse cursor. Does this software need to be rewritten from .ani?

**Comment by izayoisama0987** [comment]
Oops! When I tried it myself, I was able to change the cursor. Thank you so much for your help! Thank you very much. If you have any questions, we may ask you. I'm sorry for my poor English. With love from Japan.

**Comment by NordJan** [comment]
The .ani files are animated cursor files for Windows. Within Mousecape there is only support for its own .cape files and the abandoned Mightymouse files. Very little chance the software will be adapted soon.

**Comment by DarkMatter** [comment]
Thank you, @MUI68K!

**Comment by MUI68K** [comment]
> Thank you, @MUI68K!

You're welcome :D

**Comment by dailylama** [comment]
If you have XCode installed, select "Sign to Run Locally" for all Targets (Mousecape, helper, mousecloak)

and Product → Archive

**Comment by mac4kent** [comment]
Oh really?

**Comment by mac4kent** [comment]
I don't understand please step by step
1. Open xCode.app
2. . . .
3. . . .
4. . . .
5. . . .

**Comment by squm** [comment]
> 1. Open xCode.app
1. Click on Mousecape.xcodeproj to open XCode
2. Link to explanation about “Signing & Capabilities”

[https://help.apple.com/xcode/mac/current/#/dev5a825a1ca](https://help.apple.com/xcode/mac/current/#/dev5a825a1ca)

unset “Automatically manage signing”, Team: None, Provisioning Profile: None

3. for all targets
link to description and screenshots on Targets
[https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/WorkingwithTargets.html](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/WorkingwithTargets.html)

**Comment by mac4kent** [comment]
1. Click on Mousecape.xcodeproj to open XCode
I don't know where link.

**Comment by NordJan** [comment]
You have to download the source, from https://github.com/alexzielenski/Mousecape/releases.
The .xcodeproj is inside the .zip (or .tar.gz)

**Comment by mac4kent** [comment]
sure

**Comment by mac4kent** [comment]
Open xcode.app and appear mousecape then click (PLAY) is error I don't understand.
![image](https://user-images.githubusercontent.com/4253305/84521264-98aa0e00-ac89-11ea-958f-8318d073f68d.png)

**Comment by MUI68K** [comment]
@mac4kent Find and delete the Sparkle.framework... Look at the PROJECT headline in the 2nd sidebar from the left.. find the Info/Build Settings/ etc.. look for Codesigning and disable the codesigning for what is in red. and choose none, then look a little below that red text with the developer codesigning and look for a menu that describes what to build for.. select to have it run Locally. If you click on the red error symbol you'll see what's wrong

**Comment by mac4kent** [comment]
Thank you for your link that much help on video I follow exactly your direct and I am show you more error.
Click (!) on top appear list
Your video between 1:04 - 1:08
Me is MacOS 10.15.5

xCode.app latest version beta 
![image](https://user-images.githubusercontent.com/4253305/84541280-f3546180-acab-11ea-8175-db0b8aa12327.png)


![image](https://user-images.githubusercontent.com/4253305/84541095-850f9f00-acab-11ea-9992-e3c89821b331.png)

**Comment by MUI68K** [comment]
@mac4kent try clicking the error messages in the sidebar - these should take you to the problem at hand.. the sparkle framework is taken away by highlighting it and clicking the minus button when you get to the error after pressing the error message in the sidebar. Also go through the PROJECT list again.. the mousecloak has to have to be changed to run locally and removal of the developer ID.

**Comment by alexzielenski** [comment]
The 0.0.6 build of Mousecape was inadvertently signed with an adhoc certificate. This was suspicious to Apple's systems.

The new build 1813 (new numbering system) should be properly signed
