### ISSUE TITLE
Why mouse capes look like this?

### ISSUE THREAD

**Issue by lmaoguy123** [alexzielenski/Mousecape#122]
When i download the files, they download as zip files and i cant extract it

**Comment by NordJan** [comment]
Please specify which files you download, in order to help.

**Comment by lmaoguy123** [comment]
http://www.rw-designer.com/cursor-library
I found the tutorial on youtube, and if you go on this page you can download cursors, but, they doesn't download as .cape files

**Comment by NordJan** [comment]
I have checked. When you download the file, it is a .zip file and it contains .ani files, those are animated cursors for Windows. So, not for Mousecape, you need .cape files.
You can try to find one of your likings at https://github.com/MUI68K/Mousecape-Throwback
Click on the .cape file you want, in the next window, look for the Raw-button and right-click to do Save as .., then it will download the .cape. Cheers.

**Comment by lmaoguy123** [comment]
Thanks you so much :)

**Comment by lmaoguy123** [comment]
hey, i just downloaded a cape file and now, its look grey and not black

**Comment by lmaoguy123** [comment]
look 
<img width="63" alt="Capture d’écran 2020-05-27 à 11 32 37" src="https://user-images.githubusercontent.com/66006649/83002868-da8e4f80-a00d-11ea-9e4b-9431359e3cc8.png">
<img width="37" alt="Capture d’écran 2020-05-27 à 11 32 56" src="https://user-images.githubusercontent.com/66006649/83002886-de21d680-a00d-11ea-8bd2-def9f06db4f9.png">

**Comment by NordJan** [comment]
It looks like this is the one you want: https://github.com/MUI68K/Mousecape-Throwback/blob/master/Mousecape-capes/com.allan.memori.65D1FD09-BC83-4E21-88C1-4E561A35397C.cape
After downloading and adding to Mousecape, you also must select it. It seems you have another one selected.
Hope this helps.

**Comment by MUI68K** [comment]
> look
> <img alt="Capture d’écran 2020-05-27 à 11 32 37" width="63" src="https://user-images.githubusercontent.com/66006649/83002868-da8e4f80-a00d-11ea-9e4b-9431359e3cc8.png"> the normal
> <img alt="Capture d’écran 2020-05-27 à 11 32 56" width="37" src="https://user-images.githubusercontent.com/66006649/83002886-de21d680-a00d-11ea-8bd2-def9f06db4f9.png"> my cape

This issue if one I've dealt with for a long time  the fading of the mouse cursors. The solution came with using a newer Mousecape than what I had at the time because Alex, the author of Mousecape, developed and fixed what was wrong..

That issue is here:
https://github.com/alexzielenski/Mousecape/issues/89

Are you using Mousecape 0.0.6b2 and what macOS version are you using?

**Comment by lmaoguy123** [comment]
I downloaded mouscape 2, thanks you
