### ISSUE TITLE
How i can have dark theme on mousecape?

### ISSUE THREAD

**Issue by lmaoguy123** [alexzielenski/Mousecape#124]
I just looked the screenshot about mousecape and it look in. dark theme... Someone can explain me how?

**Comment by MUI68K** [comment]
You'll need macOS Mojave or macOS Catalina for that. If you're on High Sierra then I don't think dark mode is that well implemented yet. Wasn't there a command that could give dark mode to some apps on High Sierra too? 
There's the command listed here: 
https://www.mackungfu.org/GetdarkmodeonmacOSHighSierrawiththishack

But if you can apply it to a single app then that's great. 

In Xcode there's the option to build with dark mode as the default - I learned that I can set the window frame to what ever I want after I took a glance at the source code for Mousecape yesterday and updated some things in it - based on the latest 0.0.6 code.

**Comment by lmaoguy123** [comment]
Ok thanks but when i do the command and restart mac the text look upside down xd but thanks
