### ISSUE TITLE
How can I create a set  of capes (other than just "arrow" type)?

### ISSUE THREAD

**Issue by AtinaOkluog** [alexzielenski/Mousecape#125]
Hi there!
Love what you're doing it is so COOL!!! 
I have tried to create my own set of capes (different types) but it doesn't work. "Arrow" is recognized, however, other types are not... What am I doing wrong? 
(P.S. I am not code savvy, I was able, however, to import some of your cape sets. Absolutely LOVE your "metro modern" style, wish they came in different colours though)
Any help in creating a set is highly appreciated. :) THANKS!

**Comment by MUI68K** [comment]
Thank you for your appreciation of the Metro Modern cursors. I'm glad you like them. ❤️ 

Btw.. I don't know if you meant to open this issue on my repo for all my Mousecape cursor sets?
Alex is the author of the Mousecape application and I am the author of Metro Modern and more 🙂 

About the creation of cursor sets.. are there specific cursors that doesn't activate like they should? Like window resizing or hyperlink(the standard hand) cursor?

**Comment by AtinaOkluog** [comment]
I apologize for confusion and opening the "issue" in the wrong place. 
My praise is for both of you :) 
I started with "arrow", then added new type "link" added different image... Basically I was adding the most common ones, and after adding about 2-3 of them, I didn't not see any of them activate except the "arrow".  Does it make sense?

**Comment by MUI68K** [comment]
Sure, it makes sense.. the Link is the alias cursor and the Pointing cursor is the "hover over links in browser" I can't say if that's some of the things that's going wrong - it was for me in the very beginning - I was always confusing the two.

It does all make sense - is there any way you could send the ones you want for each of the elements you're trying to change and I can see if there's a match here on my system?

There shouldn't be any issues - the only thing I have issues with are animations currently. Static images such as a transparent PNG image or TIFF image shouldn't be an issue getting applied.

I will also screen record the session for you so that we're on the same page if you'd like.

**Comment by AtinaOkluog** [comment]
I was trying to adapt the following cursor set (http://www.rw-designer.com/cursor-set/coffee-cup) manually. I'd copy and images and add them manually to the mousecape (as it is shown in here https://www.youtube.com/watch?v=fUPOL8gwTk8).  If there is an easier way to "grab"  cursor sets from the website mentioned above and convert them to the "cape" friendly, I'd love to learn about it. :)
Also, is there existing "cape" file I can find for Solara cursor mention in the previous thread (https://github.com/alexzielenski/Mousecape/issues/120)?  Thanks a bunch for your help!!!!

**Comment by MUI68K** [comment]
> I was trying to adapt the following cursor set (http://www.rw-designer.com/cursor-set/coffee-cup) manually. I'd copy and images and add them manually to the mousecape (as it is shown in here https://www.youtube.com/watch?v=fUPOL8gwTk8). If there is an easier way to "grab" cursor sets from the website mentioned above and convert them to the "cape" friendly, I'd love to learn about it. :)
> Also, is there existing "cape" file I can find for Solara cursor mention in the previous thread (#120)? Thanks a bunch for your help!!!!

I think the Solara cape is still available as an attachment in this comment:
https://github.com/alexzielenski/Mousecape/issues/84#issuecomment-346994372

The friendliness of converting? yeah,, rename all .cur that you download to .png and they should be easy to put in Mousecape dropzones for your chosen cursor ie. the coffee cup one.

Small video linked here( (my Jumpshare account)
https://jumpshare.com/v/DDsR9fCviTHQymZJpqXw+/coffee-cup.mov

**Comment by AtinaOkluog** [comment]
Excellent! Thank you! It was extremely helpful.
