### ISSUE TITLE
MacOS Catalina 

### ISSUE THREAD

**Issue by hdulam** [alexzielenski/Mousecape#126]
It doesn't work in the lastest version of MacOS. The pointer changes but after clicking on anything else, it goes back to the MacOS default.

**Comment by MUI68K** [comment]
Is it possible for you to describe this a little more? 

using what cursor set and using what version of Catalina - I have 10.15.5 and all is OK and everything applies and doesn't disappear after clicking anything.

Please elaborate if you can.

**Comment by hdulam** [comment]
I have MacOS Catalina 10.15.5:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.3 GHz

I downloaded it from: https://github.com/alexzielenski/Mousecape/releases
(Pre-built versions)

I tried both 0.0.5 and 0.0.6. 

I uploaded a screen recording (ZIP file because github doesnt allow to upload movs...)

Thanks again for all your great work!!

[Screen Recording 2020-06-13 at 16.43.22.mov.zip](https://github.com/alexzielenski/Mousecape/files/4775409/Screen.Recording.2020-06-13.at.16.43.22.mov.zip)

**Comment by MUI68K** [comment]
Have you tried enabling Retina?

**Comment by hdulam** [comment]
Ok now it says HD. Fixed. I added the 2x... I also clicked on retina... 

This is the cursor im trying to use:
![77411-0](https://user-images.githubusercontent.com/50688196/84579044-a0a4a380-ad98-11ea-87ef-6c91e326d9c1.png)

**Comment by MUI68K** [comment]
> Ok now it says HD. Fixed. I added the 2x... I also clicked on retina...
> 
> This is the cursor im trying to use:
> ![77411-0](https://user-images.githubusercontent.com/50688196/84579044-a0a4a380-ad98-11ea-87ef-6c91e326d9c1.png)
> 
> The Svanslös does work! There might be something wrong with my files. Sorry to bother you!!

I'm only re-opening this to show you my take.

I think that first you need to make the 48px be 32px by changing the canvas for the image.
This is a quick movie https://jumpshare.com/v/OvT5JV9Vskv7CAqq3DCp

[notmine-cape.zip](https://github.com/alexzielenski/Mousecape/files/4775498/notmine-cape.zip)


![32](https://user-images.githubusercontent.com/60530401/84579500-74a41500-adce-11ea-814f-f9e58233c872.png)
![64](https://user-images.githubusercontent.com/60530401/84579501-753cab80-adce-11ea-8e4c-4d280a41d0cf.png)

**Comment by hdulam** [comment]
Thank you!! -> One last thing that might help others!! 
Another thing I was doing wrong that I realized when importing the Svanslös is that I didnt mark it as "arrow" if it is unknown it would cause that error... 

Thanks again!!
