### ISSUE TITLE
cape not applying

### ISSUE THREAD

**Issue by annieruthlaing** [alexzielenski/Mousecape#130]
i've gone through all the steps but as i apply or double tap my cursor doesn't change and in the top right its says there is no applied cape

**Comment by MUI68K** [comment]
How are your cursors set up? Are you making one from scratch or using some pre-built cape?

**Comment by annieruthlaing** [comment]
making one from scratch with a cursor from the rw website

**Comment by annieruthlaing** [comment]
also now i deleted the app and it won't let me open the updated version because its saying it needs to be updated and apple can't check it for maliciousness

**Comment by MUI68K** [comment]
Are the naming correct? "Arrow" and such?

**Comment by annieruthlaing** [comment]
yeah i did it on arrow

**Comment by MUI68K** [comment]
> also now i deleted the app and it won't let me open the updated version because its saying it needs to be updated and apple can't check it for maliciousness

I think this is helped by downloading the latest Mousecape from here https://github.com/alexzielenski/Mousecape/releases

**Comment by MUI68K** [comment]
> yeah i did it on arrow

Could you, if you are comfortable with it, share the cape or images/link you are working from?

**Comment by annieruthlaing** [comment]
the latest one isn't working for some reason.. 
i used this website for the cursor 
http://www.rw-designer.com/cursor-lib...

**Comment by annieruthlaing** [comment]
i can't share the cape as i can no longer open the software

**Comment by MUI68K** [comment]
> i can't share the cape as i can no longer open the software

That's okay.. You can always find your capes in your Application Support folder under Mousecape/capes/

**Comment by annieruthlaing** [comment]
where can i find application support? sorry!

**Comment by MUI68K** [comment]
> the latest one isn't working for some reason..
> i used this website for the cursor
> http://www.rw-designer.com/cursor-lib...

This link is truncated so the link doesn't go anywhere on the rw-designer website other than a 404 page :) 

Odd about the fact that the most recent Mousecape won't open - it was programmed by Alex to go around all those issues.

**Comment by annieruthlaing** [comment]
http://www.rw-designer.com/cursor-library

**Comment by MUI68K** [comment]
> where can i find application support? sorry!

Oh,, your home folder there's your username and the Application Support files.
`/Users/Library/Application Support/Mousecape/capes/`

**Comment by annieruthlaing** [comment]
i can't see mousecape in the application support

**Comment by MUI68K** [comment]
> i can't see mousecape in the application support
Try seeing here 
<img width="1290" alt="Screen Shot 2020-07-09 at 02 28 54" src="https://user-images.githubusercontent.com/60530401/86983403-10d1f980-c18c-11ea-88f5-3dc7cffc1bfd.png">

**Comment by annieruthlaing** [comment]
when i click my home folder, the library folder isn't there?

**Comment by annieruthlaing** [comment]
i have managed to open an old version of the software i think, i will try again and share the cape afterwards

**Comment by MUI68K** [comment]
> when i click my home folder, the library folder isn't there?

You can use the keyboard shortcut Command+J to get the View Options window up for that particular folder and check the box I highlighted.. Or go to the menubar when in Finder and the Library folder there as a direct access.

But, I also think that the issue with Mousecape not opening anymore with the absolute latest release is worrying

**Comment by annieruthlaing** [comment]
how can i share my cape with you?

**Comment by MUI68K** [comment]
I will try creating a new cape with these
http://www.rw-designer.com/cursor-set/hello-kitty-3

My most own personal cape is working too - so I wouldn't expect issues.

There's a small wiki about converting the animated Windows cursors to macOS for use with Mousecape. Have you seen it? It's written up by yours truly

**Comment by annieruthlaing** [comment]
i will look that up now!

**Comment by MUI68K** [comment]
> how can i share my cape with you?

You would have to compress it after you have chosen to show the cape with Show in Finder from the Mousecape menubar. 
Then share the zip file by dragging it onto the placeholder in the comment section here when you reply. cape files aren't directly allowed

**Comment by annieruthlaing** [comment]
[local.annieruthlaing.Unnamed.615945465.632429.cape.zip](https://github.com/alexzielenski/Mousecape/files/4893868/local.annieruthlaing.Unnamed.615945465.632429.cape.zip)

**Comment by MUI68K** [comment]
> [local.annieruthlaing.Unnamed.615945465.632429.cape.zip](https://github.com/alexzielenski/Mousecape/files/4893868/local.annieruthlaing.Unnamed.615945465.632429.cape.zip)

I can understand why you're not seeing anything - there's no cursors? 
<img width="455" alt="Screen Shot 2020-07-09 at 02 42 58" src="https://user-images.githubusercontent.com/60530401/86984123-fac53880-c18d-11ea-979c-1df414c1193c.png">

**Comment by annieruthlaing** [comment]
when i open it on my mac there's a cursor there for me?

**Comment by annieruthlaing** [comment]
!!!! i think it might be because i was used an animated cursor?

**Comment by MUI68K** [comment]
I see that the file is populated with images, but I don't see anything - I can see the Arrow entry but it's not populated here.

Hmm... the crash was specific about Mousecape being considered malware? That's an issue that was dealt with. Could you use AppCleaner from [http://freemacsoft.net/appcleaner/](url) to clear out the Mousecape application and the cache files but leave out the Application Support folder that contains your actual capes to try and get a relatively clean slate?

**Comment by annieruthlaing** [comment]
the app cleaner link won't work

**Comment by MUI68K** [comment]
try again

**Comment by annieruthlaing** [comment]
:/ i cant locate the mousecape app now. sorry for being so annoying. i emptied my bin?

**Comment by MUI68K** [comment]
> :/ i cant locate the mousecape app now. sorry for being so annoying. i emptied my bin?

https://github.com/alexzielenski/Mousecape/releases/download/1813/Mousecape_1813.zip

Is the direct link... you hopefully check all the boxes and emptied your Bin too? You should keep that one checkmark empty like in the screenshot :D

**Comment by annieruthlaing** [comment]
i cleaned it.. what next!

**Comment by MUI68K** [comment]
> i cleaned it.. what next!

Download Mousecape from the above link and try once more what you was occupied with earlier; making a mouse cursor set and applying it. I would like to help still if you would like me to? Basically - Mousecape 1813 should be downloaded and we're off again

**Comment by annieruthlaing** [comment]
okay, i'm probably going to need your assistance so bare with me whilst i download it :)

**Comment by annieruthlaing** [comment]
ugh we're back at square one now. i can't open the latest version

**Comment by MUI68K** [comment]
How very strange. 🤔  You are on macOS Catalina?

**Comment by annieruthlaing** [comment]
yep, version 10.15.5

**Comment by annieruthlaing** [comment]
and it does the same thing

**Comment by annieruthlaing** [comment]
wait i did it, its open now

**Comment by annieruthlaing** [comment]
IT WORKED!!!!!!!!!!!!!!!!!

**Comment by MUI68K** [comment]
> wait i did it, its open now

Great 👍  Now the cursors themselves. It all works fine?

**Comment by annieruthlaing** [comment]
finally!!!!!!!!! you are honestly an angel omg. i feel so stupid but you are amazing for helping me for so long!

**Comment by annieruthlaing** [comment]
yep, new cursor is working

**Comment by MUI68K** [comment]
You are welcome.. software is being software 😁  feel free to reach out again any time

**Comment by annieruthlaing** [comment]
i will do! thank you...? what was your name

**Comment by MUI68K** [comment]
> i will do! thank you...? what was your name

Allan - I made the Mousecape icon and is a collaborator here 😄  Humblebrag

**Comment by annieruthlaing** [comment]
well you're amazing, thank you
