### ISSUE TITLE
How to implement pointing hand and open hand?

### ISSUE THREAD

**Issue by Jordan-Sun** [alexzielenski/Mousecape#132]
The mousecape release version only provides closed, counting up and counting down type cursor. However, the mouse cursor uses the pointing hand and open hand. Is there a way that I can implement pointing hand and open hand using mousecape?

**Comment by MUI68K** [comment]
Hi,

I hope that I'm understanding this right. In my latest Mousecape cursors I've implemented the Open Hand cursor and pointing cursor. Pointing meaning URL's and such, correct?

https://www.deviantart.com/allannyholm/art/Luxus-cape-release-link-to-Windows-tryout-848929521

and out from Deviantart: https://jumpshare.com/v/rHHQmJAzNC38i342aiOY


<img width="526" alt="Screen Shot 2020-07-20 at 01 05 37" src="https://user-images.githubusercontent.com/60530401/87887436-78f2cc00-ca25-11ea-8abf-622bc723c461.png">

<img width="526" alt="Screen Shot 2020-07-20 at 01 04 50" src="https://user-images.githubusercontent.com/60530401/87887433-77290880-ca25-11ea-9658-f51ea086310b.png">

**Comment by Jordan-Sun** [comment]
Never mind, I was finding "open hand" instead of "open". Thank you!
