### ISSUE TITLE
animated cursors not applying

### ISSUE THREAD

**Issue by frederik69420** [alexzielenski/Mousecape#134]
hello, I am trying to apply an animated cursor but it will just give the normal mac os x cursor Idk how to fix this pls help? [here](https://youtu.be/neNG5RWE8gw) is proof

**Comment by MUI68K** [comment]
Looks like you're using a retina Mac.  Did you remember to include the Retina cursor? It didn't look that way in your video.

**Comment by frederik69420** [comment]
24 just makes it scroll between frames

**Comment by frederik69420** [comment]
and even fewer frames make it worse

**Comment by MUI68K** [comment]
I haven't been able to go anywhere above 28 frames my self as Mousecape tells me that I can't type in a larger number than 24. That's what I am saying.

I can't tell if you are using a Retina Mac?

**Comment by frederik69420** [comment]
I am using a retina mac I couldn't do any other stuff for my animated cursor to be able to work/show on mousecape so I dragged the gif into mousecape and it let me use 28 frames because the gif has 28 frames anyways idk what is happening?

**Comment by frederik69420** [comment]
ok I only put in 24 frames and it works now sorry for wasting time

**Comment by richardswesterhof** [comment]
Hi, sorry for reviving an old thread but this is still an issue. A workaround for anyone else finding this is to use a divisor of the amount of frames that is below 24 and increase the frame duration to make up for it. E.g. one of my cursors had 60 frames, so I used 20 frames and multiplied the duration by 3
