### ISSUE TITLE
mousecape is open, but nothing pops up?

### ISSUE THREAD

**Issue by bunnieboo** [alexzielenski/Mousecape#142]
so I wanted to change my cursor today to something new, when I opened the mousecape application on my MacBook (operating system is Mojave) mouse cape was opened, I could see the app name on my upper right corner next to the apple icon, but nothing loads up. I right clicked the application icon and clicked show all windows and it says no available windows. I’m stuck with one cursor and the only way I can load up that one cursor is by clicking mousecape> Install helper tool 

just to be clear, the application is running. it doesn’t need to be force quit , the only issue is that the windows/actual application will not display no matter what I try. Maybe I need to run a command or something? This is really troubling

**Comment by NordJan** [comment]
This looks a lot like the previous issue (https://github.com/alexzielenski/Mousecape/issues/141). So have a look there and perform my last suggestion (upload your .cape here and try the .cape I uploaded).

**Comment by bunnieboo** [comment]
just to clarify by .cape do you mean the cursor I downloaded and used? Or, is it something else (I’m not really great with these kinds of things so please bear with me)

**Comment by bunnieboo** [comment]
also I downloaded the zip just now and opened it, nothing changed ):

**Comment by NordJan** [comment]
In response to your last 2 item:
- by .cape I mean a file with the extension .cape, to identify it as being usable by Mousecape (ie Solara.SkinPlant.cape for my favorite cursorset). For most people they are stored in de folder  /Library/Application Support/Mousecape/capes. So have a look there to see if there are any .cape files 
- after "opening" the .zip a .cape is extracted. Did you doublle-click that .cape?
Hold on, eventually we will nail this down.

**Comment by bunnieboo** [comment]
there are 3 cape files! I did make 3 capes prior to this issue happening, and yes I double clicked the .cape, it opened Mousecape and there were still no windows ):

**Comment by bunnieboo** [comment]
turns out deleting Mousecape with appdelete and reinstalling fixed the problem!! haha it was that simple

**Comment by NumberInacave** [comment]
this worked for me too; I was having the same problem

**Comment by angeloftheweb** [comment]
I tried downloading the appcleaner and I'm not sure if I downloaded the right one or not but it still didn't work for me. this is the one I downloaded![image](https://github.com/user-attachments/assets/da45de2a-6b81-4e8e-a72b-0c6419113faf)

**Comment by mouryaagrawal2014-ctrl** [comment]
cvjhdsusdiuhodjeijfouhgfsdihugsdhjsdufsdhfbdshbsdjcbiydscnsdjncdsbcsdj
