### ISSUE TITLE
When you find something clickable something it changes back (I cant fix or find an option

### ISSUE THREAD

**Issue by darealblack** [alexzielenski/Mousecape#148]
So when I Hover over clickable it would change back to a hand. Are there any fixes or solutions? Thanks.
Im on macOS Btw

Thank you!
dareal_black

**Comment by Shashank-Prasanna** [comment]
Did you already set a cursor for the hand? If you didn't, do that.

**Comment by darealblack** [comment]
Im sorry, i was dumb i didnt realise you could do that
