### ISSUE TITLE
Animated Cursor is Really Stretched Out

### ISSUE THREAD

**Issue by SpyGuy0215** [alexzielenski/Mousecape#149]
Basically the title. My animated cursor is *really* stretched out vertically. Whenever I try to change the size, it just changes back to the default size. I used ezgif.com to make a sprite sheet, which is all the sprites in an animation (in this case, the cursor) into a vertical list. It's 24 frames exactly. The animation part works fine, I just need to resize it. How would I do that?

**Comment by Serralq** [comment]
The solution is to change the size of the image. I think when you first put a sprite in it sets the whole image as a single frame and then you change the frame count but didn't change the total size. For example my normal sprite is has a height of 44.4 here 
<img width="637" alt="Xnip2022-03-13_10-30-27" src="https://user-images.githubusercontent.com/24797641/158064364-7c2d7b4d-3a54-42d5-af1d-d4e50209063b.png">
but if I put in a four image sprite the total size is way too big (177.6)
![Busy](https://user-images.githubusercontent.com/24797641/158064382-57d1f857-4ae6-4760-94f7-ba942eda6ed2.png)
<img width="637" alt="Xnip2022-03-13_10-31-36" src="https://user-images.githubusercontent.com/24797641/158064408-58e0b745-13e7-48c4-a6d3-c1c302beef59.png">
and it doesn't automatically change when the frame count is fixed so I have to do it manually. 
<img width="637" alt="Xnip2022-03-13_10-33-12" src="https://user-images.githubusercontent.com/24797641/158064470-839317c4-08db-4d53-9bcf-04295df876c8.png">

**Comment by SpyGuy0215** [comment]
If only I had known this before I got my news Windows computer in August...xD well let me close the issue, maybe it can help somebody else out in the future.
