### ISSUE TITLE
Cursor Says it's applied but not visible 

### ISSUE THREAD

**Issue by kitty7968** [alexzielenski/Mousecape#151]
I downloaded mousecape and applied a cursor, however the default cursor from my Mac is all that appears. I have uinstalled and reinstalled the application that didn't solve the problem. I also attempted javascript and that didn't work either. Any tips?

**Comment by NordJan** [comment]
Yes, question: what version of OSX/MacOS are you on?
Tip: supply a screenshot of the Mousecape-app window to see how this looks, then we can look further.

**Comment by kitty7968** [comment]
I am on a IMac- Big Sur version 11.2.3
<img width="709" alt="Screen Shot 2021-03-25 at 5 29 54 PM" src="https://user-images.githubusercontent.com/81389282/112552016-14e08e80-8d90-11eb-9b6a-5965fb5b9ccf.png">

**Comment by NordJan** [comment]
Aha, your .cape only contains 1 type of cursor. It helps when it contains different types, for Arrow, Busy, Crosshair and so. Check screenshot.
When you select 'fox', go to the menu Capes and then Edit (or Cmd+E) and see which type is attached to your 1 image. You might want to change this to Arrow to see it. Let me know if this helps.
![Screenshot 2021-03-25 at 23 36 37](https://user-images.githubusercontent.com/8850154/112552710-88e85a00-8dc3-11eb-8dda-3f2ac4d6fcd7.jpg)

**Comment by kitty7968** [comment]
Thank you so much, having multiple types of cursors worked.
