### ISSUE TITLE
Where can I find more capes?

### ISSUE THREAD

**Issue by tsuliwaensis** [alexzielenski/Mousecape#154]
Where can I find more capes for Mousecape? I've searched but haven't turned up anything.

**Comment by NordJan** [comment]
You can search this forum, eg:
- https://github.com/alexzielenski/Mousecape/issues/120
- https://github.com/alexzielenski/Mousecape/issues/138
or https://www.letmegooglethat.com/?q=mousecape+capes

**Comment by tsuliwaensis** [comment]
A lot of the capes in those links are no longer available. I only found one that was still downloadable. So that doesn't really answer the question

**Comment by NordJan** [comment]
Allen Nyholm Nielsen has updated his collection of Mousecape cursor sets in 2021 and now contains 32 .cape files: https://www.deviantart.com/allannyholm/art/Mousecape-Throwback-Mac-cursors-781872368 and download.
So, does that really answer the question now?
I am also willing to upload my favourite (Solara by SkinPlant, made from https://www.deviantart.com/skinplant/art/Solara-1928792), just ask. Cheers, Nord

**Comment by tsuliwaensis** [comment]
Thank you. I couldn't download Allen Nyholm Nielsen's set yesterday.

**Comment by NordJan** [comment]
This is a hint on how/where to download the file:
![Screenshot 2021-04-06 at 21 56 05](https://user-images.githubusercontent.com/8850154/113770989-211b0300-9723-11eb-9756-54a17dff6ade.jpg)

**Comment by tsuliwaensis** [comment]
The first time I tried to download the file, after post #2, the file failed to download. However, I was able to succesfully download it yesterday.

**Comment by Yusef-Le-Potato** [comment]
thx
