### ISSUE TITLE
Not importing ani and crs files

### ISSUE THREAD

**Issue by expressfrog** [alexzielenski/Mousecape#156]
I downloaded an ani and crs file and try to move it to your app Mousecape... It doesn't work! So can you please allow your app to support ani and crs files?

**Comment by expressfrog** [comment]
Still not working

**Comment by NordJan** [comment]
And probably never will. MouseCape is a macOS application, .ani is a Windows fileformat. I understand that you might be disappointed, but if it doesn't work like you want, try to use it as it does. And it does work, for many of us.

**Comment by VisualisationExpo** [comment]
There's ways for this... I made a wiki about it long ago on an old account that I took down. The gist of the wiki is to use 2 or so applications for macOS to do the best you can to divide the .ani into single PNG files and then merge them again within Mousecape.

There's a project on here on GitHub called CursorCreate
https://github.com/isaacrobinson2000/CursorCreate

I haven't checked if the author has updated it for Big Sur - it will work on Catalina and Mojave
