### ISSUE TITLE
Can you add control over the cursor color of text input?

### ISSUE THREAD

**Issue by GanZhiXiong** [alexzielenski/Mousecape#170]
Terminal  can do it. I want to globally set the cursor for macOS text input?

![image](https://user-images.githubusercontent.com/27394631/147831043-c9c145ba-3265-4f58-9dc8-0588ea8cf7df.png)

**Comment by alexzielenski** [comment]
Unfortunately this is something specific to the terminal application and not something that will ever be within Mousecape's capability to do system-wide.
