### ISSUE TITLE
Mousecape won't work

### ISSUE THREAD

**Issue by Izzydabro** [alexzielenski/Mousecape#180]
I used mouscape last year for a few months, but then after a few months I stopped using it. Then I came back today to try it again a year later, but when I click apply it won't work. It only shows my regular cursor. But when I put my cursor on the dock the different cursor will show, and also when I do mission control. But it does not show on my desktop screen. Is this a bug? Please help me find a solution to this. Thanks.

**Comment by NordJan** [comment]
You could first try to restore to the default cursor set, in the Mousecape application hit Cmd+R, and see if all cursors are right. If so, next you can choose your favorite set and apply, you should see a green check mark on the right side of the set.
Let us know how you are doing. Cheers, Nord

**Comment by Izzydabro** [comment]
Hi @NordJan, I did what you said, but still my applied cursor does not show and still shows the default cursor.

<img width="600" alt="Screenshot 2022-03-31 at 09 56 03" src="https://user-images.githubusercontent.com/100755298/160960713-f90378d8-2861-405e-94bc-ba731e3de217.png">

**Comment by NordJan** [comment]
The screenshot was a really good idea, this reveals a lot. It looks like your cursor set has only 1 cursor. What is the name/type of this particular cursor (I think it should be 'Arrow')?
Since there is only 1 cursor, the rest (Crosshair, IBeam, Pointing, Wait, etc) will be unchanged.
So, look for the name of your cursor and probably change it to Arrow, save and re-apply. See what that does.

**Comment by Izzydabro** [comment]
It's type is already an arrow

**Comment by NordJan** [comment]
Next step (never give up): could you zip your .cape file and post it here, so I (or others) can check the behavior on another system? Eventually we will sort this out.

**Comment by Izzydabro** [comment]
[local.isabellelau.Unnamed.670311061.933043.cape.zip](https://github.com/alexzielenski/Mousecape/files/8397334/local.isabellelau.Unnamed.670311061.933043.cape.zip)

**Comment by Izzydabro** [comment]
[local.ee.Unnamed.670311061.933043.cape.zip](https://github.com/alexzielenski/Mousecape/files/8397361/local.ee.Unnamed.670311061.933043.cape.zip)

**Comment by NordJan** [comment]
Thanks, but this probably does not help you: I imported your .cape and applied and the arrow is visible, see screenshot in the red circle.
![Screenshot 2022-04-01 at 14 25 28](https://user-images.githubusercontent.com/8850154/161263363-b92f6b5b-c736-4803-87d3-fb291414f456.jpg)
I will try other things and let you know if/when I find something. Cheers, Nord

**Comment by NordJan** [comment]
In the mean time, here is something for you to try out, to see if Mousecape does work properly on your system. I have included my favorite cursor set, Solara. Please import this and see if it shows after being applied.
[Solara.SkinPlant.cape.zip](https://github.com/alexzielenski/Mousecape/files/8397622/Solara.SkinPlant.cape.zip)

**Comment by Izzydabro** [comment]
Nope, it still doesn't work. I tried applying my old ones and it didn't work. That's why I permanently deleted mousecape and reinstalled it so that's why I only have one cursor. But the cape still does not show.

**Comment by NordJan** [comment]
Could you do the following:
- open/start Mousecape
- in the menu, do Capes/Restore Defaults (or just hit Cmd+R)
- in the menu, do Capes/Dump Cursors...
- send a screenshot of the Mousecape window, showing all the cursor sets.
?

**Comment by Izzydabro** [comment]
<img width="706" alt="Screenshot 2022-04-02 at 10 44 53 AM" src="https://user-images.githubusercontent.com/100755298/161362811-06e9356a-9aeb-42f5-9026-988e79251fa2.png">

**Comment by NordJan** [comment]
Hmm, your and my Cursor Dump seem the same, except for at least 1 cursor (first from the left), which happens to be the Arrow. So the Restore Defaults might not work completely. Your Arrow seems to belong to a different set
What I would do is, choose and apply Solara and see what the Arrow is, and then do another Restore Defaults and a Cursor Dump and compare the 2 dumps. They should be identical, as they are done after de restore, but I suspect the Arrow might be "persistent".
Then we will go from there.

**Comment by NordJan** [comment]
Aha, I just thought of 'one more thing': in the System Preferences there is an option to change the fill and outline of your cursor, there you can also reset this:
![Screenshot 2022-04-03 at 00 07 00](https://user-images.githubusercontent.com/8850154/161402967-1725119f-b1eb-47a7-aff1-dab503010ff7.jpg)
Please look it up and try the reset and then try to load your .cape again.
Cheers, Nord

**Comment by Izzydabro** [comment]
<img width="681" alt="Screenshot 2022-04-03 at 10 15 16 AM" src="https://user-images.githubusercontent.com/100755298/161408279-44e46327-4379-4087-ab7c-70fa6833da25.png">

**Comment by Izzydabro** [comment]
Thank you so much, @NordJan after changing my mouse colour the capes finally show. Thanks again.

**Comment by NordJan** [comment]
Haha, nice. Final words on this one before it can be closed.
As I said: never give up (success is: failing so much, until you can't anymore (bad translation from dutch, but anyways)).
My analysis on this issue: the setting in the System Preference is in higher priority to the Restore Defaults from within Mousecape. If there is a command for this reset, it could be added to Mousecape, but since this is the first time this issue has occurred, we will just remember it. Our toolbox of "It does not work" is been expanded a little again.
Happy Mousecaping. Cheers, Nord
