### ISSUE TITLE
Quick way to switch left vs. right hand?

### ISSUE THREAD

**Issue by zhouk** [alexzielenski/Mousecape#209]
Is there a quick way to switch left / right hand without opening up Mousecape? 

I switch between two hands regularly to avoid fatigue and right now I'm using the Automator to emulate clicks to the preferences panel then apply the current cursor set again to make it effective. It comes with a lag of 30 - 60 seconds.

Is there a faster way to do this without having to open up the Mousecape UI?  I tried to look into the arguments of mousecloak and it doesn't look like there are options to switch hands.

**Comment by Diskutant** [comment]
you could set the preference using defaults like so:

`defaults write com.alexzielenski.Mousecape MCHandedness -int 1`

0 = right
1 = left

and then reapply the cape using 

`mousecloak -a /path/to/your/favourite.cape`

put that all in a script which reads the current MCHandedness value and sets the other one should make it quite fast.

**Comment by zhouk** [comment]
Works like a charm, thank you for sharing the knowledge @Diskutant !
