### ISSUE TITLE
cursor only applies for a minute

### ISSUE THREAD

**Issue by G1RL2** [alexzielenski/Mousecape#224]
title. i can only apply my cursors for a split second, then it goes back to normal. 
here is a video.

https://github.com/alexzielenski/Mousecape/assets/123906448/60c8dbfe-0201-4628-84d1-aa6bc2c11b55

**Comment by Bellavene** [comment]
Maybe because it wasn't updated for quite some time. Here is arm ready
[Mousecape.zip](https://github.com/user-attachments/files/15751604/Mousecape.zip)
