### ISSUE TITLE
How to convert WIN cursors in .cape?

### ISSUE THREAD

**Issue by Jvanda** [alexzielenski/Mousecape#235]
[Aero.zip](https://github.com/user-attachments/files/15988981/Aero.zip)
[MacMini.zip](https://github.com/user-attachments/files/15988983/MacMini.zip)
Hello,

Please advise me how can I convert my favourite cursors in to .cape file?
I have these (attached) for about 10 years now and very get used to it. 
New to mac.

Thank You for any support.

**Comment by NordJan** [comment]
Dear Jvanda, how have you used these cursor sets? Any application in Windows? MightyMouse? That would be fine, as MightyMouse cursors can be imported in MouseCape.
Otherwise, you can start a New Cape file and one by one import the .cur files to the specific cursors. You can check in other .cape files how the cursors are named. Cheers, Nord

**Comment by Jvanda** [comment]
> how have you used these cursor sets? Any application in Windows? MightyMouse?

Hello NordJan, 
Thank You for Your prompt reply.
I changed the cursors in WIN settings, without any additional application. It was way more easy than on Mac.

New Cape file?

**Comment by NordJan** [comment]
After creating a new .cape file, you will have to add different cursors with the + bottomleft, see attached screenshot, within this cursor, you can drag the desired .cur file.
![Screenshot 2024-06-26 at 16 25 12](https://github.com/alexzielenski/Mousecape/assets/8850154/6b039532-f4bd-4e20-8533-3bb2653c1437)

PS: beware of comments like "It was way more easy than on Mac." ;-)

**Comment by NordJan** [comment]
O, and under Capes, there is the Dump Cursors ..., which makes a .cape of your current cursor set. If you do that with the default, you can see how all different cursors are named. This one is for free.

**Comment by Jvanda** [comment]
NordJan, thank You. I have almost created my .cape. Just having issues with .ani. How to convert these in .cur?
[Ani - Busy and Working.zip](https://github.com/user-attachments/files/15993342/Ani.-.Busy.and.Working.zip)

**Comment by NordJan** [comment]
Let me Google that for you ;-)
I searched for "convert .ani" and found some online converters, tried the first one (https://online.reaconverter.com/convert/ani-to-png) and submitted your .ani's.
Here are the results, you can use them to make your animated cursor in MouseCape (see, https://github.com/alexzielenski/Mousecape#how-do-animated-cursors-work). Cheers, Nord
[reaConverter-2024-06-27-bbedf08a7d80.zip](https://github.com/user-attachments/files/16010759/reaConverter-2024-06-27-bbedf08a7d80.zip)

**Comment by Jvanda** [comment]
Hello NordJan, I have to thank You for Your patience and assistance. I was not aware that .png fits for cape.
Though, with You help, I finalize it, but I cannot apply it - the skin doesn't change.
[JV_Nice_TRY.cape.zip](https://github.com/user-attachments/files/16014452/JV_Nice_TRY.cape.zip)

**Comment by NordJan** [comment]
Hoi Jvanda, thanks for the compliment, sometimes patience is my middle name (sometimes not).
I can apply the .cape you sent, see screenshot. To apply double-click the cape bar, or right-click on that cape and choose Apply, that's it.
Tip: if you want an animated cursor, take the individual .png from earlier and stack them vertically, see previous link (and keep track of how many you stack for the number of frames).
![Screenshot 2024-06-27 at 15 13 07](https://github.com/alexzielenski/Mousecape/assets/8850154/f54eef0c-e86b-46e3-ab70-2546020d8afd)

**Comment by NordJan** [comment]
I have version 1813. But also, I am on macOS Sonoma 14.5. 
I guess I am lukcy to have MouseCape working, as there are many people experiencing problems, cursor resets and all. This is freeware, provided as is, so as long as it keeps working, I am happy.

**Comment by mmemoo** [comment]
!! shameless self promo incoming !! : 
i made a tool to convert windows cursor packs to mousecape cape files 
https://github.com/mmemoo/capeify
i hope it helps you!
