### ISSUE TITLE
totally new to mousecape, how do i get this windows 8 cursor pack into my mousecape and working as my macOS cursor?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [alexzielenski/Mousecape#239]
here's the cursor pack [windows_8_small_cursors_by_derprogamer2000_d7xalhm.zip](https://github.com/user-attachments/files/16120795/windows_8_small_cursors_by_derprogamer2000_d7xalhm.zip). ive tried following [these directions](https://github.com/alexzielenski/Mousecape/issues/235#issuecomment-2191860322) but it doesn't work when i drag the `aero_busy.ani` file into the 1x spot (see screen recording below & notice how it lets me drag the `aero_arrow.cur` file but not the `aero_busy.ani` file). any help is so so appreciated, im really looking forward to using mousecape! 

https://github.com/alexzielenski/Mousecape/assets/43555540/bcfffaf6-67f6-4de5-a927-37e1f32977e8

**Comment by NordJan** [comment]
Dear ComfortableMilk4454 (?), MouseCape does accept .cur as a file type, but not .ani, that is a Windows format. Look at the directions above and the documentation here at github: for animated cursors you need a vertical stack of .png's. If you Google, you can find online 'services' to convert .ani to indivdual files and after that you can construct the stack yourself. Cheers, Nord

**Comment by ComfortableMilk4454** [comment]
Tysm. How do I construct the stack myself after converting the file? Is that in the documentation? Also where exactly is the documentation lol

**Comment by NordJan** [comment]
LMGTFY: https://github.com/alexzielenski/Mousecape?tab=readme-ov-file#how-do-animated-cursors-work
If you plan to have 7 frames in the animation, you need 7 separate files and next stack them vertically, which means 1st frame is the top, 2nd frame is below the first and so on. So, if your individual files are 32x32, the resulting stack should be 32 width x 224 (7x32) height.

**Comment by ComfortableMilk4454** [comment]
ty. i converted them to pngs but how do i stack them? don't see a button to do so
<img width="637" alt="image" src="https://github.com/alexzielenski/Mousecape/assets/43555540/100b7bdc-ceb3-4897-8589-b7349f7ae1fd">

**Comment by ComfortableMilk4454** [comment]
hey, i did some digging and found [this photoshop script](http://www.andrewnoske.com/wiki/Adobe_Photoshop_-_Scripts_Related_to_Montaging#Photoshop_Script:_Create_a_montage_from_ordered_image_tiles) to "take an ordered folder of image tiles and creates one big montage" with them. problem is, i get this error:
![image](https://github.com/alexzielenski/Mousecape/assets/43555540/56265377-2819-4170-ab83-f0744857bf89)
any ideas?

**Comment by NordJan** [comment]
No, sorry, I don't Photoshop.
I suggest you just use Preview and do some copy and paste with the individual files.
But that is about the last tip I can give.

**Comment by ComfortableMilk4454** [comment]
how do i do that with preview?

**Comment by NordJan** [comment]
Just practice ;-)
Or use any other graphics application you are comfortable with ...

**Comment by ComfortableMilk4454** [comment]
figured it out, thanks. question tho, what is this icon called in mousecape? 
<img width="38" alt="image" src="https://github.com/alexzielenski/Mousecape/assets/43555540/51ee6d5f-ce16-4c7d-88f0-1b4d125da45d">

**Comment by ComfortableMilk4454** [comment]
and what one is this called 
<img width="22" alt="image" src="https://github.com/alexzielenski/Mousecape/assets/43555540/5467f199-7583-4333-a032-3dc587f559f2">

**Comment by ComfortableMilk4454** [comment]
sorry i keep finding ones idk, which one is this one called also
<img width="24" alt="image" src="https://github.com/alexzielenski/Mousecape/assets/43555540/6124f336-c7d0-4a98-b7b9-7714f51c7645">

**Comment by NordJan** [comment]
Last hint from me (you have reached your take/give limit): first Restore Defaults, which sets all cursors back to Apple standard, then Dump Cursors..., so you can check which cursor has which name. Over and out.

**Comment by ComfortableMilk4454** [comment]
Fuck is wrong with you "you have reached your take/give limit", fucking robot lol

**Comment by NordJan** [comment]
Wow wow, that is a not a nice way to say thank you. 
What I meant was that this was my last reply to you.
Cheers, Nord

**Comment by ComfortableMilk4454** [comment]
Sorry that’s why i deleted it. I thought u were trying to be rude mb

**Comment by ComfortableMilk4454** [comment]
Thanks for all ur help I appreciate it

**Comment by NordJan** [comment]
Haha, I am from Rotterdam, we never try to be rude, if we want to, we just are, no pretending. This is also somewhat of a joke (just to be sure ).
Apologies accepted. Mousecape is a nice tool, enhancing the pleasure on my MBP, so that's why I try to answer a lot of questions here. But there is also value in finding things out for yourself.
Somewhere here there is a link to a lot of .cape's, see other issue.
