### ISSUE TITLE
where do i find cursor packs?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [alexzielenski/Mousecape#241]
https://duckduckgo.com/?q=mousecape+cursor+packs&t=brave&ia=web nothing really comes up when i duckduckgo mousecape cursor packs :(. ive also looked at https://github.com/alexzielenski/Mousecape/issues/120 & https://github.com/alexzielenski/Mousecape/issues/138 but theres only a few in the ones there. looked at https://www.deviantart.com/allannyholm/art/Mousecape-Throwback-Mac-cursors-781872368 but i dont like any of the choices. looking for more options. thanks so much!

**Comment by VisualisationExpo** [comment]
There's really not that many making cursor sets for use with Mousecape, but if you're handy with some Windows cursor sets, you might just be able to convert a few .cur and .ani ones.

I recently released a cursor set called GIN'24 - that's about it. I have probably a few more sets in the works. But those aren't important enough for me to finish right now.

It's tough making cursor sets that will please everyone and I'm sorry that the option in that archive wasn't to your liking. Some are also quite a bit old - I'd admit to that

What are your preferences? Each person is different and if you want to have a cursor set you truly like and can't be found or converted, then you'll best of making one of your own.

Good luck!

**Comment by VisualisationExpo** [comment]
There's an additional cursor set for both Windows and macOS here
https://dribbble.com/shots/15060105-White-HD-Cursor
