### ISSUE TITLE
FEATURE REQUEST, change cursor based on apps

### ISSUE THREAD

**Issue by revintec** [alexzielenski/Mousecape#44]
Can you add the ability to change cursor based on apps?
I've turned Terminal.app's background to black(thinks it looks cooler),
and I can't see the IBeam cursor(which is basically black) on the screem.

So I want to change to another IBeam cursor just when using Terminal.app
Tried to edit Terminal.app itself, no luck. And I don't want to affect other apps' cursor.

**Comment by alexzielenski** [comment]
While this suggestion has merit, I think it is out of the scope for this project and would overcomplicate the design idioms I've chosen.
