### ISSUE TITLE
Noob question:  How do you build without a paid membership @ Apple?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [alexzielenski/Mousecape#50]
I, like others, have a problem seeing the I beam cursor in my Pro profile in Terminal.  I would like to build your project to see how it can help me, but I can't seem to do so.
1) I don't have a certificate.
2) The Sparkle dependency is missing from the Zip and Tar.gz files.

Sorry to have to ask such a question,
Nap

**Comment by alexzielenski** [comment]
Try downloading a pre-compiled binary in the releases page of this repository: https://github.com/alexzielenski/Mousecape/releases
