### ISSUE TITLE
Size of icons / format?

### ISSUE THREAD

**Issue by fnurl** [alexzielenski/Mousecape#52]
Hi, I just found Mousecape and want to make a left handed cape, all the same icons as the default Yosemite one, but flipped. I found the "Dump" action, but I can't figure out how/if I can get the cursors from Mousecape as image files, or copy them and paste them into Photoshop etc. Would really appreciate any tips!

**Comment by alexzielenski** [comment]
I didn't think to add an option to get PNG files out. However, there is an option in Mousecape preferences that will flip the cursors horizontally for left-handed users.

**Comment by fnurl** [comment]
Perfect! I didn't see that at first. Thanks!
