### ISSUE TITLE
Cursor resets to system cursor after computer sleep

### ISSUE THREAD

**Issue by KalciferKandari** [alexzielenski/Mousecape#53]
Maybe related, cape also not applied automatically on Mousecape start

**Comment by alexzielenski** [comment]
did you install the helper tool?

**Comment by KalciferKandari** [comment]
I have now. Could you make that a bit clearer in the app? Just a dialog box when the app first opens explaining what installing it does with a 'never show me this again' checkbox or something similar.

**Comment by PCanyi** [comment]
It is the same with me.

**Comment by alexzielenski** [comment]
consolidating into #43
