### ISSUE TITLE
Change cursor when mouse clicked?

### ISSUE THREAD

**Issue by tryagains** [alexzielenski/Mousecape#54]
Hi great tool! I was wondering how to change the mouse image when the user clicks?

I changed my cursor but when I left click I want it to be different so I can see when I click. Any help?

**Comment by alexzielenski** [comment]
This is not possible without a daemon that gets universal access to your OS. I'm sure you can see how this is a security risk if arbitrary software can monitor where you're clicking and perhaps what you're typing.
