### ISSUE TITLE
Mousecape either/or

### ISSUE THREAD

**Issue by braunsys** [alexzielenski/Mousecape#55]
Excellent product, except it seems I'm only able to create one active cape, i.e. either a new "arrow" or a new "pointer" cape at one time, when I try to have both working at the same time, Mousecape only allows one to function, and the other doesn't change, and remains as the Mac default cape?
I hope this makes sense, and if there is a solution, please provide.
Thank you

**Comment by alexzielenski** [comment]
Capes are collections of cursors. When you are creating a cape, try hitting that plus button in the bottom left corner of the edit window and you will be given a new cursor to add to your cape to apply multiple at once.
