### ISSUE TITLE
Suggestion: hooks or utility for quickly switching cursors?

### ISSUE THREAD

**Issue by DmitriR** [alexzielenski/Mousecape#59]
For people using more than one character set / language, having visual feedback (in the form of, say, differently colored I-beam cursor) on which keyboard is enabled would be really nice. 

Hooking up cursor switch to the keystrokes that switch keyboards could be a simple way to do it (e.g. via Karabiner) - if there was, say, a command line utility to load a particular cursor (or cycle between two or more in a set).

Or perhaps deeper magic is possible.

**Comment by alexzielenski** [comment]
Take a look at mouse cloak, a binary embedded in the Mousecape app, it provides the command line interface you are looking for

**Comment by DmitriR** [comment]
Yes, this looks perfect! Thanks
.../Mousecape.app/Contents/MacOS/mousecloak
