### ISSUE TITLE
Mouse cape- window not showing- stuck with cape

### ISSUE THREAD

**Issue by Ender-Craft** [alexzielenski/Mousecape#61]
Hey i got mouse cape and it was working for a bit, but now it opens and shows no window. Ive tried to delete and reinstall it. Ive also tried other versions. Nothing works and I'm stuck with a mouse that i don't really want. Please help me out. Thx.

**Comment by bunam** [comment]
try to uninstall with appDelete (to find the preferences and associated files) ?

**Comment by Ender-Craft** [comment]
Where to i get app delete. I looked on the app store. its 3.99 i don't really want to pay.

**Comment by Ender-Craft** [comment]
Nvm man i got app delete. Thanks soon much dude it works now!!!!!
