### ISSUE TITLE
Not all cursors reseted to default :(

### ISSUE THREAD

**Issue by peterpaulis** [alexzielenski/Mousecape#62]
After restoring to default, the spinning wheel changed to a sand clock (like in old windows)

Is there a way to get the nice OSX spinning wheel back?

**Comment by gridsystem** [comment]
I'm experiencing this as well and it's also the beachball which hasn't reverted.

**Comment by troy1960** [comment]
same here, i really really hoping for a fix, now i have a windows 10 loader instead of the ball :( PLZ FIX

**Comment by alexzielenski** [comment]
Unfortunately it's hard to reset all the cursors to default (theres no way to find the list of every single one). Don't worry though, when you logout or reboot they will be fine. Mousecape only applies changes in-memory.
