### ISSUE TITLE
El Capitan - cursor reverts to default after restart

### ISSUE THREAD

**Issue by fnankivell** [alexzielenski/Mousecape#64]
El Capitan 10.11.3 - cursors revert to default after reboot, unistalling and reinstalling Helper tool didn't help. Everything else working fine. Thanks!

_edit_ found a workaround by manually adding com.alexzielenski.mousecloakhelper app to the login items. Installing Helper tool with Mousecape app does nothing...

**Comment by JamesLampert** [comment]
Confirmed that the above workaround seems to do the job.

**Comment by alexzielenski** [comment]
Thanks for this. It's an odd issue, Apple's ServiceManagement API is very finicky.

**Comment by ryenus** [comment]
> adding com.alexzielenski.mousecloakhelper app to the login items

What is this **com.alexzielenski.mousecloakhelper app**? 
Is it part of Mousecape? Where to find it? 

Thanks

**Comment by fnankivell** [comment]
Right-click on the Mousecape app and select "Show package content", you will then find it here:

Mousecape.app/Contents/Library/LoginItems/com.alexzielenski.mousecloakhelper.app

Manually add this app to your login items and you'll be all set!

**Comment by ELREYS** [comment]
Confirm on macOS Sierra Xcode 8.3.3, works like a charm,
Thanks for this solution, i found that if you use a yellow , icons, on the DUSK theme shows blue, really cool :)

**Comment by martin-braun** [comment]
@fnankivell I tried what you said and it did not work for me: 

<img width="546" alt="com.alexzielenski.mousecloakhelper.app are active in Login Items" src="https://user-images.githubusercontent.com/24259245/189482115-ec2331eb-a023-4b77-b764-88b5ecd480fc.png">

The only real thing that works is installing the Helper Tool, but this will open the Mousecape window on every start, I don't like this. @alexzielenski 

What can I do?
