### ISSUE TITLE
El Capitan - downscaling cursor size no longer possible

### ISSUE THREAD

**Issue by fnankivell** [alexzielenski/Mousecape#65]
El Capitan 10.11.3

The previous trick of manually entering a smaller value (0.75 for example) to downsize the cursor size no longer works in El Capitan. Upsizing is fine though, either with the slider or by entering a value (2.5 for example).

Thank you!

**Comment by alexzielenski** [comment]
This is due to constraints set by Apple I unfortunately have no control over. I suppose I could start scaling the cursor images themselves down, but I haven't really seen a demand for this sort of thing.
