### ISSUE TITLE
Might I humbly suggest a distinctive icon?

### ISSUE THREAD

**Issue by JamesLampert** [alexzielenski/Mousecape#66]
Something like:
![mousecape icon](https://cloud.githubusercontent.com/assets/3721417/13129589/bda4a9ae-d592-11e5-9e57-bc623dc9810c.png)

**Comment by alexzielenski** [comment]
lol. Unfortunately icons cost money and I'm a poor college student. You're welcome to donate one :smile:

**Comment by JamesLampert** [comment]
On 2/17/16, 5:39 PM, Alex Zielenski wrote:
> lol. Unfortunately icons cost money and I'm a poor college student. You're welcome to donate one :smile:

Ok. Here's one, a small rodent standing on a ruler, carrying a pencil 
and a paintbrush, in both a PNG and an ICNS. Derived from images that 
were explicitly marked Public Domain on Wikimedia Commons, so unlike the 
one I quickly threw together yesterday, it's utterly free from encumbrances.

I freely donate this icon to the Mousecape project.

--
James H. H. Lampert

**Comment by fnankivell** [comment]
James, I can't see your icon. Maybe because I'm new to Github and not looking at the right place?

I've been using my own home-made icon for quite some time, if you care to see. Nothing really special, simple enough to recognize it in my dock...

![mousecape_icon](https://cloud.githubusercontent.com/assets/1984285/13158379/a5431cf6-d65a-11e5-807f-ecdf05616006.png)

**Comment by slfrsn** [comment]
How about a literal interpretation of a mouse... in a cape? I can draft up a vector logo if you're interested. I have a pretty extensive background in graphic design.

**Comment by DarkMatter** [comment]
Slfrsn, as the non-maker of the application but a much-fan of it, I think you should definitely make the logo, and share it with us. :D

**Comment by gaming-hacker** [comment]
like Mighty Mouse would be cool

**Comment by DarkMatter** [comment]
I made an icon for my Mousecape app, which you can see as my profile picture:

<img width="236" alt="screen shot 2017-03-14 at 8 37 18 pm" src="https://cloud.githubusercontent.com/assets/17834193/23928440/1b32ca82-08f6-11e7-81ed-299626bb0162.png">

**Comment by ExactProbability** [comment]
One I finish the darn thing I might also have something for use with Mousecape. If only just for fun. See atttached image.
![gettingthereeventually](https://cloud.githubusercontent.com/assets/25787371/24184590/06c08ca4-0ecf-11e7-87a6-8fdac524496f.jpg)


Also, if you don't have the original MightyMouse icons from the Unsanity app then you can have get them from the attached zip.
[mightymouse-unsanity-icons.zip](https://github.com/alexzielenski/Mousecape/files/860490/mightymouse-unsanity-icons.zip)

**Comment by DarkMatter** [comment]
Looking good bro!
