### ISSUE TITLE
In El Capitan, an animated version of the default arrow causes Java applications to ignore double-clicks

### ISSUE THREAD

**Issue by JamesLampert** [alexzielenski/Mousecape#68]
I recently discovered that Java applications (e.g., KeyStore Explorer, and our own Wintouch) were ignoring double-clicks within their own user interfaces. Double-clicks in native applications and in the Finder itself were unaffected; only double-clicks within Java applications.

I realized that it started happening shortly after I updated my Mousecape to a version that actually works under El Capitan, so I tried removing the cape I'd constructed ("Willard," consisting of just an Arrow, in the shape of a small rodent with an animated wiggling tail). Double-click functionality in Java returned. So then I tried your sample cape. Double-clicks continued to work in Java.

Then I built a non-animated version of "Willard," switched to it. Double-clicks continued to work in Java, but if I switched back to the animated version of "Willard," Java once again became blind to double-clicks.

An animated GIF made from Willard (and the PNG strip for the cape) are shown below, for your edification.

![willard](https://cloud.githubusercontent.com/assets/3721417/13228640/e265c1a2-d951-11e5-89d7-3ab6feeab29e.gif) ![willard all](https://cloud.githubusercontent.com/assets/3721417/13228677/1838ab8c-d952-11e5-9d9e-1193c8339294.png)

**Comment by justin0a0** [comment]
Just gave this a go and double clicking using the mouse worked fine in java apps for me just now.
The way mousecape works is it replaces the cached images that OS X uses to draw the cursor on screen. I would assume you are using version 0.0.5 (1579).
The helper tool is still kind of finicky still so I suggest not really using it and manually applying the cursor when you reboot.
Now not to say that it may be an issue of animated capes as I have no idea how it works in depth but its using the apple default animation ability currently to animate.
Maybe Alex would have a bit more insight into why this might occur.

**Comment by JamesLampert** [comment]
All I know is that under Mountain Lion, I observed no such problems, that this only happens in Java applications that process double-clicks, and only with the animated version of my "Willard" arrow, and that my JRE is 1.7.0_09-b05.

**Comment by alexzielenski** [comment]
Does this still happen for you

**Comment by JamesLampert** [comment]
On 10/13/19 12:31 PM, Alex Zielenski wrote:
> Does this still happen for you

Unknown, I'm afraid:

I haven't tried the animated version of my mouse pointer since I first 
reported the issue, and I am now on Mojave (which has its own issues 
with Mousecape).

--
JHHL

**Comment by alexzielenski** [comment]
Mousecape 1813 should work up to Catalina. Please do come back if you ever find this issue again.
