### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by DarkMatter** [alexzielenski/Mousecape#70]
I know I'll come off as a complete newbie, but I looked online and couldn't find an answer. I created a Legend of Zelda set of capes for Mousecape, but I can't figure out how to export it in order to share it with other people. The work I did is quite nice, as I'm fairly good at Photoshop, but I'm not as clever when it comes to packaging my work for Mousecape. 

How do I do it?

**Comment by justin0a0** [comment]
Right click on cape area > Show in finder 
Cape will be highlighted :wink:

**Comment by DarkMatter** [comment]
Is that all? I see. I had done that but, it didn't seem right to me. I understand now. Thanks a lot, Justin!

**Comment by justin0a0** [comment]
Yup! 
You can double click a .cape file and it will be imported automatically.

**Comment by DarkMatter** [comment]
Right, I was aware of that. I think it was the strange name Mousecape applied to my custom capes that threw me off. Anyhow, very glad to have this sorted. Thanks, again!

**Comment by DarkMatter** [comment]
Here are links to the respective Zelda themed .capes in case people are interested:
http://sllapur.deviantart.com/art/Master-Sword-596623221
http://sllapur.deviantart.com/art/Din-s-Fire-596622144

Feel free to comment on my work. I'm keen to learn more.
