### ISSUE TITLE
0.0.5 doesn't work on Mountain Lion 10.8.5

### ISSUE THREAD

**Issue by 1-61803** [alexzielenski/Mousecape#71]
In the `Info.plist` you can read

```
    <key>LSMinimumSystemVersion</key>
    <string>10.9</string>
```

Can you compile it for 10.8 or provide some hints for doing it myself? A quick try threw a bunch of errors.

**Comment by alexzielenski** [comment]
The minimum system version is set because I use private symbols not available on 10.8.

**Comment by 1-61803** [comment]
Then you might want to correct the `README.md`.

**Comment by alexzielenski** [comment]
I believe mouse cloak - the command line tool for actually applying capes works for 10.8+ but the interface is 10.9+ - it's been a while though

**Comment by 1-61803** [comment]
A simple interface should easily compile back in 10.8. Is it possible to use Mousecape with the command line tool only?

**Comment by alexzielenski** [comment]
Yes. Again it's been a long time but `mousecloak --apply <path/to/cape>` should suffice I believe
