### ISSUE TITLE
Cursor acts weird when typing when animation

### ISSUE THREAD

**Issue by nik312123** [alexzielenski/Mousecape#75]
I am using png files to act as frames of the animated cursor. However, whenever I type anything like I am doing now, the cursor disappears for a fraction of a second per character and then goes back to normal. This issue only occurs when this is acting as a gif rather than a static image.

I am on Mac OSX El Capitan 10.11.6

Attached is a video of the problem. For some reason, QuickTime Player's Screen Recorder does not show the changing colors of my animated cursor?

I would attach the actual .cape file itself if I knew how to export it. Thanks!
[Untitled.zip](https://github.com/alexzielenski/Mousecape/files/981819/Untitled.zip)

**Comment by ExactProbability** [comment]
I would recommend creating the IBeam cursor too if you haven't done so. Also look carefully at the Frames and Duration fields in Mousecape for your particular cursor.

With my sets I don't see the issue. I'll look more carefully later on today but as of right now I don't see the issue.

**Comment by alexzielenski** [comment]
I'm really sorry but I'm not able to reproduce this. Maybe its an issue with your cape?
