### ISSUE TITLE
How do I get rid of cursorflip on my mac? 

### ISSUE THREAD

**Issue by richard00777** [alexzielenski/Mousecape#76]
I downloaded cursorflip.zip in order to change the size and shape of my cursor. 
I don't like it. 
How do I get rid of it now? 
I deleted the file, but it doesn't change anything. My cursor still appears in the shape of a Micky Mouse hand. 
Please, advice.

**Comment by alexzielenski** [comment]
Remove anything related to mouse cape from login items in system preferences under users and groups. GitHub issues are for code-specific issues. If you need help using your operating system I suggest you look elsewhere in the future.
