### ISSUE TITLE
Help: Animated Cursors

### ISSUE THREAD

**Issue by HarryAwesome06** [alexzielenski/Mousecape#78]
Hi. Before I start I have tried using the instructions given to do this but they didn't really make sense **to me**.

Long story short I click 3 frames and add the .ani, nothing shows nor did it even go through. I could use some help with .ani files on Mac OSX Sierra. I have a program to view .ani files but I can't add them into Mousecape.

Thanks. 

P.S. Here's a gif of what happens: https://gyazo.com/f0b62b0dcf88bef3f695ac78c67a98af

**Comment by alexzielenski** [comment]
1.) You can't use .ani files as images in Mousecape
2.) Your frames in the image need to be vertically stacked, not horizontally. Use cursorflip to automate this: https://github.com/alexzielenski/Mousecape/releases/tag/cflip

**Comment by HarryAwesome06** [comment]
I tried using it, nothing worked.

**Comment by alexzielenski** [comment]
What did you try?

**Comment by HarryAwesome06** [comment]
When I tried to set the area the .ani is and the cursorflip is it said that one of the areas were invalid.

**Comment by HarryAwesome06** [comment]
http://prntscr.com/g4slon

**Comment by HarryAwesome06** [comment]
I don't know why. Am I typing something wrong?

**Comment by alexzielenski** [comment]
You need to place quotes around paths in Terminal when they have spaces. Also, as I said earlier you cannot use ani files. Convert it to a png first.

**Comment by HarryAwesome06** [comment]
How do I convert it? Just change the end?

**Comment by alexzielenski** [comment]
I don't know off the top of my head. Honestly I don't think you have the technical skills necessary to safely use this product.

**Comment by HarryAwesome06** [comment]
Well. I can at least use .cur

**Comment by HarryAwesome06** [comment]
But I have one thing.

**Comment by HarryAwesome06** [comment]
I did manage to get 3 frames in .png format, don't know if that helps though.

**Comment by alexzielenski** [comment]
`.ani` and `.cur` files are for Windows or Linux cursors. I suggest you use other resources for help beyond this. Your questions are not related to Mousecape.

**Comment by alexzielenski** [comment]
If you have 3 frames you can use photoshop or something to craft a new image of each frame stacked vertically as the instructions in the readme say.

**Comment by HarryAwesome06** [comment]
If only I had Photoshop.

**Comment by alexzielenski** [comment]
if only

**Comment by HarryAwesome06** [comment]
Question, what selection from the dropdown is Text?

**Comment by ExactProbability** [comment]
IBeam - that's the text cursor.

**Comment by Pooper3000** [comment]
poop

**Comment by TheOneAndOnly-Loup** [comment]
@TailsIsAwesome I know that it's been like 5 years since you were here but if look at this [video](https://www.youtube.com/watch?v=fUPOL8gwTk8) to have the animated cursors (photoshop) or use this [video](https://www.youtube.com/watch?v=SQ7BG2iOXTE&t=1s) with gimp.
