### ISSUE TITLE
Not setting Cursor/Not changing cursor when trying to apply

### ISSUE THREAD

**Issue by 2i8** [alexzielenski/Mousecape#79]
Hi, I've tried to change my cursor on Mac, and it doesn't seem to apply when i try to apply it neither does it save my changes when i do
![screen shot 2017-09-14 at 14 57 15](https://user-images.githubusercontent.com/31948485/30414141-164736a0-995d-11e7-9804-a75d070ebbb9.png)
![screen shot 2017-09-14 at 14 57 34](https://user-images.githubusercontent.com/31948485/30414142-164de856-995d-11e7-8fa4-147598d1c0e6.png)

**Comment by alexzielenski** [comment]
The size is set to 0, try setting it to the size of the image.
