### ISSUE TITLE
Im super confused

### ISSUE THREAD

**Issue by mememeeme** [alexzielenski/Mousecape#81]
There are so many different types of cursor modes and which one do I use. I i want a click animation which mode do I use please help. I

**Comment by alexzielenski** [comment]
Sorry I've never had time to write a thorough instruction manual. The gist is this though: if you wanted your cursor to be animated, you should set the "Size" field in the edit panel to the dimensions of one frame. Then you supply an image with such frames stacked vertically on top of each other. Mousecape will slice it up for you depending on the size you had set.
