### ISSUE TITLE
Where is the "Install Helper Tool"?

### ISSUE THREAD

**Issue by adamberkey** [alexzielenski/Mousecape#82]
"It is unintrusive and works in the background. You just need to open the app, click Mousecape --> Install Helper Tool, apply your cursor and you're done!"

==

No such file in the folder.

**Comment by NordJan** [comment]
It is not a file, it is a men-item, see screenshot (when not installed the menu-item say “Install Helper Tool”).

**Comment by adamberkey** [comment]
Oops.   Thanks for pointing that out.
I couldn't figure out how to start the application, with the files shown in the archive.  And I still don't.  But I found a download elsewhere that I could actually run. 
What would be the process to actually get the application running with the download from this site since none of the files, which I could see anyway, were executable?

**Comment by NordJan** [comment]
If you go to the code section and scroll down to version 0.05, there is a Mousecape.zip with the application.
The application is really in there, it is dated 26 July 2014, I have just downloaded and checked.
