### ISSUE TITLE
Can't import capes in OSX 10.10.5 Yosemite

### ISSUE THREAD

**Issue by ranjitc** [alexzielenski/Mousecape#84]
Have tried double clicking, using import as well as just copy pasting it in the folder where dumps are created. None worked ...

**Comment by NordJan** [comment]
Dear Ranjitc,

please try to import the attached .cape (unzip first of course) and describe what is happening.
Kind regards,
Nord-Jan Vermeer

**Comment by ranjitc** [comment]
Hi,

Can't find any attachment. Sorry if I'm making a silly mistake.

Thanks for your reply!

**Comment by NordJan** [comment]
No, I am the silly one here. When answering by mail the attachment is ignored. Now the attachement is added on the forum.
Kind regards,
Nord-Jan Vermeer
[Solara.SkinPlant.cape.zip](https://github.com/alexzielenski/Mousecape/files/1503761/Solara.SkinPlant.cape.zip)

**Comment by ranjitc** [comment]
Thanks!

This worked perfectly! So, is there something different about the cape file linked in the readme? Any idea where I can search for some other cape files / icons? My main problem is that the default ibeam looks bad and is indistinguishable from the background on dark uis.

**Comment by ranjitc** [comment]
oh brilliant! thanks @NordJan ! your example cape made me realise that i can make a new cape with just the ibeam. i need not re-create *all* icons! fantastic. thanks a ton!

**Comment by NordJan** [comment]
No problem. What about sending me your problematic .cape (through Github ;-) ), so I can have a look if something is wrong with it.

**Comment by ranjitc** [comment]
I was having trouble with the cape mentioned in the Readme : [svanslosbluehazard](https://github.com/alexzielenski/Mousecape/blob/master/Mousecape/com.maxrudberg.svanslosbluehazard.cape) ...

**Comment by NordJan** [comment]
I think I tracked down the error/mistake: the link ("here for download") seems to lead to the mentioned .cape, but is a link to a webpage (on which the actual .cape can be downloaded), so right-clicking this link saves the page and not the .cape, unfortunately the page and .cape have the same name, but obviously a different content. Trying to import the page-disguished-as-cape even froze my Finder.
So, if you still want the .cape, just click th link and on the resulting page the .cape can be downloaded.
Cheers, Nord-Jan

**Comment by ranjitc** [comment]
Thanks mate, that got it working :)

**Comment by Thinkscape** [comment]
@ranjitc Could you close this issue if it's not relevant anymore?

**Comment by ranjitc** [comment]
@Thinkscape done! (sorry new to github, learning as i go along)
