### ISSUE TITLE
Empty window! Nothing to do.

### ISSUE THREAD

**Issue by ivakyb** [alexzielenski/Mousecape#85]
<img width="745" alt="default" src="https://user-images.githubusercontent.com/7225779/37571642-1750c0e2-2b08-11e8-8295-92959c0861e1.png">
    

<img width="621" alt="default" src="https://user-images.githubusercontent.com/7225779/37571646-23617a48-2b08-11e8-9d7c-a0934d6c10bd.png">

**Comment by NordJan** [comment]
Dear qywx,

you will have to import a .cape file first (Cmd+O), in order to be able to use it.
Please find attached my favourite cursor-set: Solara by Skinplant.
Hope this helps. Cheers.
Kind regards,
Nord-Jan Vermeer

**Comment by NordJan** [comment]
Direct replying does not include attachments, so here it is: Solara by Skinplant.
[Solara.SkinPlant.cape.zip](https://github.com/alexzielenski/Mousecape/files/1823186/Solara.SkinPlant.cape.zip)
Once imported, just double click to use.
Kind regards,
Nord-Jan Vermeer

**Comment by qywx** [comment]
Thank you.
