### ISSUE TITLE
LINK cursor not work for me

### ISSUE THREAD

**Issue by seboiii** [alexzielenski/Mousecape#86]
when i go on some link, the cursor not change look, please HELP!

**Comment by NordJan** [comment]
Dear seboiii,
a .cape file can contain many different modes for the cursor, eg. Arrow, Crosshair, Help, IBeam, Pointing, Wait etc. In order for the appropriate cursor to be displayed, this mode should be available in the .cape. So, open Mousecape, select your current .cape, right-click and choose Edit to find out the various modes within your cape. If Pointing and/or Link are not present, you may add them.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/8850154/38208576-d0fb5ca0-36b1-11e8-849d-0c829559db4b.png">
Hope this helps.
Kind regards,
Nord-Jan Vermeer

**Comment by alexzielenski** [comment]
Thanks for responding where I'm not available @NordJan
