### ISSUE TITLE
What is the "Type name" of Text

### ISSUE THREAD

**Issue by iamrToday** [alexzielenski/Mousecape#87]
hello , this sweet application is very useful
and I try each Type but I don't find a type for text select, text edit
it is still use MacOS's original Text cursor 

please tell me the Type name 
thank you

**Comment by NordJan** [comment]
Dear iamrToday,

what exactly do you mean by Text cursor? Could you show MasOS’s original?
Have a look at iBeam, that might be what you are looking for.

Kind regards,
Nord-Jan Vermeer

**Comment by iamrToday** [comment]
thank you!

**Comment by alexzielenski** [comment]
@NordJan damn you rock
