### ISSUE TITLE
hello , I write a Chinese GUIDE 

### ISSUE THREAD

**Issue by iamdsilver** [alexzielenski/Mousecape#88]
hello 
I do this just to say thank you 
I had follow all the GUIDE , the best way to say thank you is talk my friend
now i make it!

[here is the link for blogger](http://iamdsilver.blogspot.tw/2018/04/mousecape.html)

China fined can also download the attach file, it is written by traditional Chinese.
[mousecape.md.zip](https://github.com/alexzielenski/Mousecape/files/1924220/mousecape.md.zip)

**Comment by iamdsilver** [comment]
I also write a method to easy make animation

1. download \.ani file [form this site](http://www.rw-designer.com/cursor-library)
2. \.ani file convert to \.gif file [form this site](https://online-converting.com/image/convert2gif/)
2. \.gif file convert to \.png file [form this site](https://image.online-convert.com/convert-to-png)
3. use Gimp or photoshop even PaintBrush to make a lone line png
4. enjoy animation

**Comment by alexzielenski** [comment]
Hello, thank you for the guide. I am sorry for my absence. Unfortunately since I can't read chinese or know anyone fluent I dont feel comfortable placing it up on the main repo. If you would like to reach out and work with me more closely on this id be happy to get the guide and helper integrated.
