### ISSUE TITLE
How to know what is the "Type" meaning?

### ISSUE THREAD

**Issue by iamdsilver** [alexzielenski/Mousecape#90]
![](http://i.imgur.com/6SWaoha.jpg)
Q1.
When I reading PDF file or on Photoshop to draw,
I meet this mouse cursor
I don't know what is this type name, would someone kindly tell me the answer?

Q2.
When I meet some mouse cursor but I don't know  it's type name
I need to try each type one by one
is there any website or document to list all of the origin Mac cursor and the Mousecape cursor type(name)?
i had try to use [Open Cursor Library](http://www.rw-designer.com/cursor-library) to search keyword but the site is written by Windows' cursor name.
thank you

**Comment by NordJan** [comment]
A1: crosshair
A2: don’t know.
Cheers

**Comment by iamdsilver** [comment]
thank you for replying soon
but it is not crosshair
I had already set it to be crosshair but with no effect

**Comment by NordJan** [comment]
Then it might be “Cell” or “Cell XOR”.
But to me it still looks like a crosshair ;-)

**Comment by iamdsilver** [comment]
ha ha... it still not works  
and actually to say, I don't know when the 'Cell' happen and what it means
if convenient , could you and someone kindly tell me the following type means and when it will appear?
I make this Table and write what I know
and you can download the .zip file to edit the .md file 
then past and reply on GitHub issue
(My English is broken, you can edit what I write anywhere)
thank you

no |Type name | means | origin Mac sorsor<br> like this
---:|:----------|:-----------------|-----------|
0  | Alias |
1  | Arrow |regular cursor |![](http://www.rw-designer.com/cursor-view/99977.png)
2  |Busy |  
3  | camera |
4  | camera | when screenshot by cmd + shift + 4 +blank |
5  | Cell |
6  | Cell XOR |
7  | Closed |
8  | Copy |
9  | Copy Drag | when I drag .cur file to Mousecape's 1x, 2x but I don't know NO.8
10  | Counting Down |
11  | Counting up |
12  | Counting up/down |
13  | crosshair |
14  | crosshair2 |
15  | Ctx Arraw |
16  | Ctx Menu |
17  | Empty |
18  | Forbidden | Prohibition of the selection of symbols |![](http://www.rw-designer.com/cursor-view/48360.png)
19  | Help | just as the question mark | ![](http://www.rw-designer.com/cursor-view/48354.png)
20  | IBeam | text write(but in GitHub website or SubLime Text 3, it's fail) | ![](http://www.rw-designer.com/cursor-view/48358.png)
21  | IBeam H  | 
22  | IBeanXOR |
23  | Link | I dont's know, it's not web link
24  | Move |
25  | Open |
26  | Pointing | website Link to click | ![](http://www.rw-designer.com/cursor-view/99976.png)
27  | Proof |
28  | Resize Series |
29  | Wait | I don't know what it is different with 'busy' | ![](http://www.rw-designer.com/cursor-view/48356.png)
30  | Windows Series |
30  | Zoom In |
31  | Zoom Out |



[Type List.md.zip](https://github.com/alexzielenski/Mousecape/files/1957524/Type.List.md.zip)

**Comment by alexzielenski** [comment]
You can perform a "Cursor Dump" from within Mousecape to see what Apple has mapped to all of the cursors. In menu choose "Capes -> Dump Cursors..."

**Comment by 7sDream** [comment]
https://support.apple.com/guide/mac-help/pointers-in-macos-mh35695/mac

Just for a reference.

**Comment by banana-slug-woo** [comment]
I don't know much about this either but thank you for telling me which one the ibeam is
