### ISSUE TITLE
Isn't compatible with MacOS Mojave?

### ISSUE THREAD

**Issue by justbrooklee** [alexzielenski/Mousecape#93]
I recently updated to Mojave and tried applying a new cape, the file format is .cur and I set the size to {32, 32} and applied it, but no change. Is this due to Mojave. I've tried doing research on it, but it seems there has been no posts yet. Can anyone give me info or something else to try?

**Comment by NordJan** [comment]
As a result of your posting, I installed MouseCape on my Mojave VM and my favourite .cape (Solara)  installed fine, although it is a little pale in colour.
Could you upload the .cur file you are trying to install? I will test this then.
Kind regards,
Nord-Jan Vermeer

**Comment by sanssecours** [comment]
On my computer Mousecape works without any problems (macOS Mojave 10.14, Build `18A391`):

![mouse cap](https://user-images.githubusercontent.com/691989/47636932-5ab2b180-db5a-11e8-9d0d-80ed208a861d.png)

. I use the cursor set [Svanslös Blue](
https://github.com/alexzielenski/Mousecape/blob/master/Mousecape/com.maxrudberg.svanslosbluehazard.cape) mentioned in the [ReadMe](https://github.com/alexzielenski/Mousecape#where-do-i-get-cursors). Maybe that cursor set works for you too…

**Comment by alexzielenski** [comment]
You cannot use .cur files in mousecape

**Comment by expressfrog** [comment]
You mean you can't use .ani alenzenski? because you actually can use .cur files.
