### ISSUE TITLE
Mousecloak Helper Memory Leak

### ISSUE THREAD

**Issue by ledlamp** [alexzielenski/Mousecape#94]
It appears that the helper endlessly consumes memory without releasing it. The memory usage of com.alexzielenski.mousecloakhelper on my system has been slowly increasing, and is now at 408.8MB after 11 days of uptime.

![image](https://user-images.githubusercontent.com/24686877/48042727-dc48a780-e137-11e8-848d-12084b54aee0.png)

**Comment by NordJan** [comment]
Hmm, your issue made me look, but with almost 8 days uptime, I find a very different picture:
![screen shot 2018-11-07 at 13 17 42](https://user-images.githubusercontent.com/8850154/48135293-cef8fd80-e29c-11e8-9a3d-483769d0a196.jpg)
I will keep a close watch on this and report back in about 3 days.

**Comment by NordJan** [comment]
Four days later, now 11 days uptime:
![screen shot 2018-11-11 at 16 00 06](https://user-images.githubusercontent.com/8850154/48314530-2532ad00-e5cb-11e8-9faa-226dcc9e859a.jpg)
I am on MacOS Mojave 10.14.1, so I guess you could be right about the OS. Cheers.

**Comment by ledlamp** [comment]
Oh, another thing; I use two user accounts, so maybe the issue is caused by using a different user than the one mousecloakhelper is used in.

**Comment by alexzielenski** [comment]
Does this still happen for you? I've taken a look around and anywhere Mousecape does not use ARC in its helper tool its very strict about releasing allocated objects.

**Comment by alexzielenski** [comment]
I'm pretty confident 21626bfc19f95090f9dcf79fa01da242f8370e17 fixed this. New release build will be uploaded soon so re-open if it is not fixed.
