### ISSUE TITLE
Cursors feel faded/decompressed when using Retina versions

### ISSUE THREAD

**Issue by kcmannem** [alexzielenski/Mousecape#99]
I have a retina MacBook Pro connected to a non-retina monitor. The default cursors when applied in the "HD" format are slightly faded in color (hardly noticeable on the retina screen. The only sign is that the Mickey Mouse hand has 3 gray lines on the glove instead of black lines). Once you move your cursor to the non-retina display, the cursors look terribly aliased and faded. 

TEMP FIX: When I disabled the "HD" cursors and moved back to "SD" ones, they were pretty much perfect on both displays (negligible distortion on non-retina displays).

**Comment by KICKFLIP85** [comment]
the temp fix doesn't work for me... anyone has a fix? or maybe a patch? I'm using a MacBook Air 5, early 2015 laptop.

**Comment by interactiveRob** [comment]
If it helps at all, this method helped me get a sharp cursor from something I was designing as a vector. Just two overlapping circles.

- Add only a 5x or 10x image for the cursor, leave 1x and 2x blank 
- No solid fills or solid borders, make everything at least slightly transparent.

**Comment by alexzielenski** [comment]
Did the changes from #89 sort this out?

**Comment by kcmannem** [comment]
@alexzilenski nope still happen. Using the work around I mentioned in my post.

**Comment by alexzielenski** [comment]
I don't understand your workaround fully. What do you mean by you disable HD cursors? You unticked the checkbox in the edit panel?

**Comment by kcmannem** [comment]
@alexzielenski yes the SD cursors had a less noticeable faded effect to them.

**Comment by alexzielenski** [comment]
I don't quite understand how that affected anything - that checkbox is cosmetic purely used to show "HD" or "SD" badges in the library view. The checkbox value is not read from when applying capes.

**Comment by kcmannem** [comment]
@alexzielenski I was going to try and reproduce it but it looks like the app crashes in Catalina when you try to apply a cape. 

Are you seeing the effect (the bug not the workaround)  on your end ? If it helps your debug I found the effect most noticeable on non-retina screens. Its more subtle on retina screens. If you try to apply the default cursor, you'll notice that the lines in the middle of the mickymouse hand are gray instead of black. The effect is a lot more blown out when you move the cursor to say an external display which is non-retina.

**Comment by alexzielenski** [comment]
This is solved since 0.0.6
